"""훈련과정 샘플 데이터셋 (100개).

NCS 대분류 코드 기준:
  01 사업관리, 02 경영회계사무, 03 금융보험, 04 교육자연사회과학
  05 법률경찰소방행정국방, 06 보건의료, 07 사회복지종교
  08 문화예술디자인방송, 09 운전운송, 10 영업판매
  11 경비청소, 12 이용숙박여행오락스포츠
  13 음식서비스, 14 건설, 15 기계, 16 재료
  17 화학, 18 섬유의복, 19 전기전자, 20 정보통신
  21 식품가공, 22 인쇄목재가구공예, 23 환경에너지안전
  24 농림어업
"""
from sqlalchemy.orm import Session
from app.repositories import program_repo

SAMPLE_PROGRAMS: list[dict] = [

    # ── 20 정보통신 (25개) ──────────────────────────────────────────────────
    {
        "title": "AI 서비스 백엔드 개발자 양성과정",
        "provider": "K-디지털 훈련 센터",
        "program_type": "kdt",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 강남",
        "summary": "Python, FastAPI, PostgreSQL, Docker를 중심으로 AI 백엔드 서비스를 구현하는 실무 과정입니다.",
        "target_audience": "백엔드 개발 직무를 준비하는 구직자",
        "skills": "Python FastAPI PostgreSQL Docker REST API",
        "benefits": "실전 프로젝트, 포트폴리오 코칭, 취업 연계",
        "schedule": "12주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-ict-001",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["백엔드", "Python", "FastAPI", "AI"],
    },
    {
        "title": "풀스택 웹 개발 부트캠프",
        "provider": "코드팩토리 아카데미",
        "program_type": "kdt",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 마포",
        "summary": "React, Node.js, MySQL을 활용한 풀스택 웹 애플리케이션 개발 능력을 기릅니다.",
        "target_audience": "웹 개발 입문자 및 전환 희망자",
        "skills": "React Node.js MySQL JavaScript HTML CSS",
        "benefits": "팀 프로젝트, 코드 리뷰, 취업 멘토링",
        "schedule": "16주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-ict-002",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["풀스택", "React", "Node.js", "웹개발"],
    },
    {
        "title": "생성형 AI 애플리케이션 개발 과정",
        "provider": "AI 인재개발원",
        "program_type": "kdt",
        "category": "국민내일배움카드 훈련과정",
        "location": "경기 판교",
        "summary": "LangChain, OpenAI API, RAG, 벡터DB를 활용한 생성형 AI 서비스 구현 과정입니다.",
        "target_audience": "AI 서비스 개발에 관심 있는 개발자",
        "skills": "LangChain OpenAI RAG pgvector Python",
        "benefits": "기업 연계 프로젝트, 포트폴리오 완성",
        "schedule": "10주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-ict-003",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["생성형AI", "LLM", "RAG", "LangChain"],
    },
    {
        "title": "클라우드 인프라 엔지니어 양성과정",
        "provider": "AWS 공인 훈련기관",
        "program_type": "kdt",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 종로",
        "summary": "AWS, Kubernetes, Terraform을 활용한 클라우드 인프라 설계 및 운영 능력을 키웁니다.",
        "target_audience": "클라우드 인프라 직무 준비자",
        "skills": "AWS Kubernetes Terraform Docker CI/CD Linux",
        "benefits": "AWS 자격증 취득 지원, 실습 환경 제공",
        "schedule": "12주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-ict-004",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["클라우드", "AWS", "Kubernetes", "인프라"],
    },
    {
        "title": "데이터 엔지니어링 실무 과정",
        "provider": "빅데이터 교육원",
        "program_type": "kdt",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 여의도",
        "summary": "Spark, Kafka, Airflow, Hadoop을 활용한 대용량 데이터 파이프라인 구축을 배웁니다.",
        "target_audience": "데이터 엔지니어 직무 전환 희망자",
        "skills": "Spark Kafka Airflow Hadoop Python SQL",
        "benefits": "실무 프로젝트, 데이터 파이프라인 포트폴리오",
        "schedule": "14주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-ict-005",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["데이터엔지니어링", "Spark", "Kafka", "빅데이터"],
    },
    {
        "title": "머신러닝·딥러닝 엔지니어 양성과정",
        "provider": "딥러닝 아카데미",
        "program_type": "kdt",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 서초",
        "summary": "PyTorch, TensorFlow, scikit-learn을 이용한 ML/DL 모델 개발 및 배포 과정입니다.",
        "target_audience": "AI/ML 엔지니어 희망자",
        "skills": "PyTorch TensorFlow scikit-learn Python NumPy",
        "benefits": "캐글 실습, 논문 구현, 포트폴리오",
        "schedule": "16주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-ict-006",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["머신러닝", "딥러닝", "PyTorch", "AI"],
    },
    {
        "title": "iOS/Android 앱 개발 과정",
        "provider": "모바일 개발 스쿨",
        "program_type": "kdt",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 강북",
        "summary": "Swift, Kotlin, Flutter를 활용한 모바일 앱 개발 실무 과정입니다.",
        "target_audience": "모바일 앱 개발자 지망생",
        "skills": "Swift Kotlin Flutter Dart Firebase",
        "benefits": "앱스토어 출시 경험, 포트폴리오",
        "schedule": "12주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-ict-007",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["모바일", "iOS", "Android", "Flutter"],
    },
    {
        "title": "DevSecOps 보안 개발 과정",
        "provider": "정보보안 아카데미",
        "program_type": "kdt",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 구로",
        "summary": "CI/CD 파이프라인에 보안을 통합하는 DevSecOps 실무 역량을 기릅니다.",
        "target_audience": "보안 개발자, 클라우드 보안 직무 희망자",
        "skills": "DevSecOps SAST DAST Kubernetes Security OWASP",
        "benefits": "보안 자격증 취득 지원, 실습 환경",
        "schedule": "10주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-ict-008",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["보안", "DevSecOps", "클라우드보안"],
    },
    {
        "title": "SQL·데이터 분석 입문 과정",
        "provider": "데이터 스쿨",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "온라인",
        "summary": "SQL, Python, Pandas, 시각화를 활용한 데이터 분석 기초부터 실무까지 배웁니다.",
        "target_audience": "비개발 직군의 데이터 분석 역량 강화 희망자",
        "skills": "SQL Python Pandas Matplotlib Tableau",
        "benefits": "실무 데이터 과제, 분석 포트폴리오",
        "schedule": "8주 · 주 4일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-ict-009",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["데이터분석", "SQL", "Python", "입문"],
    },
    {
        "title": "UI/UX 디자인 실무 과정",
        "provider": "디자인 컨버지",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 홍대",
        "summary": "Figma, Adobe XD를 활용한 UX 리서치, 와이어프레임, 프로토타이핑 실무를 배웁니다.",
        "target_audience": "UI/UX 디자이너 지망생, 개발자 전환 디자이너",
        "skills": "Figma Adobe XD UX Research Prototyping",
        "benefits": "포트폴리오 완성, 현업 디자이너 멘토링",
        "schedule": "10주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-ict-010",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["UIUX", "Figma", "디자인", "프로토타이핑"],
    },
    {
        "title": "네트워크 관리사 취득 과정",
        "provider": "IT 자격증 학원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "부산 서면",
        "summary": "네트워크 관리사 2급·1급 자격증 취득을 목표로 TCP/IP, 라우팅, 스위칭을 배웁니다.",
        "target_audience": "네트워크 엔지니어 희망자, 자격증 취득 희망자",
        "skills": "TCP/IP 라우팅 스위칭 네트워크 보안 CCNA",
        "benefits": "자격증 취득 보장반, 실습 장비 제공",
        "schedule": "8주 · 주 3일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-ict-011",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["네트워크", "자격증", "CCNA", "네트워크관리사"],
    },
    {
        "title": "정보처리기사 취득 준비과정",
        "provider": "자격증 합격 아카데미",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "대구 동성로",
        "summary": "정보처리기사 필기·실기 완벽 대비 과정입니다. 알고리즘, DB, 운영체제 등 핵심 이론을 다룹니다.",
        "target_audience": "IT 직무 취업을 위해 정보처리기사가 필요한 구직자",
        "skills": "알고리즘 데이터베이스 운영체제 소프트웨어공학 네트워크",
        "benefits": "기출문제 풀이, 모의고사, 합격 보장반",
        "schedule": "6주 · 주 5일", "tuition": "50,000원",  "url": "",
        "source": "sample", "external_id": "s-ict-012",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["정보처리기사", "자격증", "IT자격증"],
    },
    {
        "title": "게임 클라이언트 프로그래머 양성과정",
        "provider": "게임 아카데미",
        "program_type": "kdt",
        "category": "국민내일배움카드 훈련과정",
        "location": "경기 성남",
        "summary": "Unity, Unreal Engine을 활용한 게임 클라이언트 개발 실무 과정입니다.",
        "target_audience": "게임 개발자 지망생",
        "skills": "Unity C# Unreal Engine C++ 게임수학",
        "benefits": "게임 빌드 포트폴리오, 게임사 채용 연계",
        "schedule": "24주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-ict-013",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["게임개발", "Unity", "C#", "Unreal"],
    },
    {
        "title": "블록체인 개발자 양성과정",
        "provider": "블록체인 캠퍼스",
        "program_type": "kdt",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 은평",
        "summary": "Solidity, Ethereum, NFT, DeFi 등 블록체인 애플리케이션 개발 전 과정을 배웁니다.",
        "target_audience": "블록체인 개발자 전환 희망자",
        "skills": "Solidity Ethereum Web3.js Hardhat NFT",
        "benefits": "탈중앙화 앱 프로젝트, 포트폴리오",
        "schedule": "12주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-ict-014",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["블록체인", "Solidity", "Web3", "NFT"],
    },
    {
        "title": "사이버보안 전문가 양성과정",
        "provider": "정보보호 인재개발원",
        "program_type": "kdt",
        "category": "국민내일배움카드 훈련과정",
        "location": "대전 유성",
        "summary": "모의해킹, 취약점 분석, 디지털 포렌식, 보안 관제를 망라한 종합 사이버보안 과정입니다.",
        "target_audience": "사이버보안 전문가 지망생",
        "skills": "침투테스트 취약점분석 포렌식 보안관제 Kali Linux",
        "benefits": "정보보안기사 취득 지원, 보안 기업 연계",
        "schedule": "20주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-ict-015",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["사이버보안", "모의해킹", "정보보안기사"],
    },

    # ── 15 기계 (10개) ──────────────────────────────────────────────────────
    {
        "title": "CNC 선반·밀링 조작 실무과정",
        "provider": "한국기계산업진흥회 훈련원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "인천 남동",
        "summary": "CNC 선반과 밀링 머신 프로그래밍 및 조작 능력을 기르는 실습 중심 과정입니다.",
        "target_audience": "기계 가공 직무 취업 희망자",
        "skills": "CNC선반 CNC밀링 G-code 도면해독 측정기",
        "benefits": "기계가공기능사 취득 지원, 실습 장비 완비",
        "schedule": "10주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-mec-001",
        "ncs_code": "15", "ncs_name": "기계",
        "tags": ["CNC", "선반", "밀링", "기계가공"],
    },
    {
        "title": "산업용 로봇 프로그래밍 과정",
        "provider": "스마트제조 아카데미",
        "program_type": "kdt",
        "category": "국민내일배움카드 훈련과정",
        "location": "울산 북구",
        "summary": "FANUC, ABB, KUKA 산업용 로봇 티칭 및 PLC 연동 프로그래밍 실무를 배웁니다.",
        "target_audience": "스마트공장 로봇 운용 직무 희망자",
        "skills": "산업용로봇 PLC 로봇티칭 자동화 스마트팩토리",
        "benefits": "로봇 운용기능사 취득 지원, 현장 실습",
        "schedule": "12주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-mec-002",
        "ncs_code": "15", "ncs_name": "기계",
        "tags": ["산업용로봇", "PLC", "스마트팩토리", "자동화"],
    },
    {
        "title": "기계설계 CAD/CAM 실무과정",
        "provider": "기계설계 직업훈련원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "경기 안산",
        "summary": "AutoCAD, SolidWorks, CATIA를 활용한 기계 부품 설계 및 도면 작성 과정입니다.",
        "target_audience": "기계설계 직무 취업 준비자",
        "skills": "AutoCAD SolidWorks CATIA 도면작성 GD&T",
        "benefits": "기계설계산업기사 취득 지원",
        "schedule": "12주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-mec-003",
        "ncs_code": "15", "ncs_name": "기계",
        "tags": ["CAD", "SolidWorks", "기계설계", "도면"],
    },
    {
        "title": "용접 기능사 취득 과정",
        "provider": "대한용접협회 훈련원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "경남 창원",
        "summary": "피복아크용접, MIG/MAG, TIG 용접 실기 능력을 기르고 용접기능사 자격을 취득합니다.",
        "target_audience": "용접 기능직 취업 희망자",
        "skills": "피복아크용접 MIG TIG 가스용접 도면해독",
        "benefits": "용접기능사 합격 보장반",
        "schedule": "8주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-mec-004",
        "ncs_code": "15", "ncs_name": "기계",
        "tags": ["용접", "용접기능사", "MIG", "TIG"],
    },
    {
        "title": "공조냉동기계기사 취득 과정",
        "provider": "에너지설비 훈련원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 노원",
        "summary": "공조냉동기계기사 필기·실기 준비 과정으로 냉동공학, 열역학, 공조설비를 다룹니다.",
        "target_audience": "냉동·공조 설비 직무 희망자",
        "skills": "냉동공학 공조설비 열역학 유체역학",
        "benefits": "기사 시험 완벽 대비, 실습 장비",
        "schedule": "10주 · 주 4일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-mec-005",
        "ncs_code": "15", "ncs_name": "기계",
        "tags": ["공조냉동", "냉동기계기사", "설비"],
    },

    # ── 19 전기전자 (10개) ──────────────────────────────────────────────────
    {
        "title": "전기기사 취득 준비과정",
        "provider": "한국전기기술인협회 교육원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 동작",
        "summary": "전기기사 필기·실기 완벽 대비 과정입니다. 회로이론, 전기기기, 전력공학, 제어공학을 다룹니다.",
        "target_audience": "전기기사 자격 취득 희망자",
        "skills": "회로이론 전기기기 전력공학 전기설비 제어공학",
        "benefits": "합격 보장반, 기출문제 집중 풀이",
        "schedule": "12주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-elec-001",
        "ncs_code": "19", "ncs_name": "전기전자",
        "tags": ["전기기사", "전기자격증", "전력공학"],
    },
    {
        "title": "PLC 자동화 제어 실무과정",
        "provider": "자동화제어 직업훈련원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "경기 화성",
        "summary": "지멘스·미쓰비시·LS 산전 PLC 프로그래밍과 HMI 설계를 중심으로 자동화 설비를 배웁니다.",
        "target_audience": "자동화 제어 직무 취업 희망자",
        "skills": "PLC HMI 인버터 센서 자동화설비",
        "benefits": "전기기능사 취득 지원, 실습 장비",
        "schedule": "10주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-elec-002",
        "ncs_code": "19", "ncs_name": "전기전자",
        "tags": ["PLC", "자동화", "HMI", "전기제어"],
    },
    {
        "title": "반도체 공정 장비 운용 과정",
        "provider": "반도체 인재개발원",
        "program_type": "kdt",
        "category": "국민내일배움카드 훈련과정",
        "location": "경기 평택",
        "summary": "반도체 포토, 식각, 증착, 세정 공정과 장비 운용 실무 능력을 기릅니다.",
        "target_audience": "반도체 제조 직무 취업 희망자",
        "skills": "반도체공정 포토리소그래피 식각 CVD 클린룸",
        "benefits": "반도체 기업 채용 연계",
        "schedule": "12주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-elec-003",
        "ncs_code": "19", "ncs_name": "전기전자",
        "tags": ["반도체", "공정", "삼성전자", "SK하이닉스"],
    },
    {
        "title": "임베디드 시스템 개발 과정",
        "provider": "임베디드 개발 아카데미",
        "program_type": "kdt",
        "category": "국민내일배움카드 훈련과정",
        "location": "대전 대덕",
        "summary": "C언어, ARM Cortex, RTOS, IoT를 활용한 임베디드 소프트웨어 개발 실무 과정입니다.",
        "target_audience": "임베디드 SW 개발자 지망생",
        "skills": "C언어 ARM RTOS IoT UART SPI I2C",
        "benefits": "임베디드 기업 연계, 포트폴리오",
        "schedule": "16주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-elec-004",
        "ncs_code": "19", "ncs_name": "전기전자",
        "tags": ["임베디드", "C언어", "IoT", "ARM"],
    },
    {
        "title": "전기공사기사 취득 과정",
        "provider": "전기공사 교육원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "인천 남동",
        "summary": "전기공사기사 필기·실기 대비 과정으로 내선공사, 외선공사, 전기설비설계를 배웁니다.",
        "target_audience": "전기공사 현장 기술자 희망자",
        "skills": "내선공사 외선공사 전기설비설계 배선설계",
        "benefits": "합격 보장반, 기출 집중 훈련",
        "schedule": "10주 · 주 4일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-elec-005",
        "ncs_code": "19", "ncs_name": "전기전자",
        "tags": ["전기공사기사", "전기설비", "전기자격증"],
    },

    # ── 14 건설 (10개) ──────────────────────────────────────────────────────
    {
        "title": "건축설계 BIM 실무과정",
        "provider": "건축설계 아카데미",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 강동",
        "summary": "Revit, ArchiCAD를 활용한 BIM 기반 건축 설계 실무 능력을 배웁니다.",
        "target_audience": "건축설계 직무 희망자",
        "skills": "Revit ArchiCAD BIM AutoCAD 건축도면",
        "benefits": "건축사사무소 연계, 포트폴리오",
        "schedule": "12주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-con-001",
        "ncs_code": "14", "ncs_name": "건설",
        "tags": ["BIM", "Revit", "건축설계", "ArchiCAD"],
    },
    {
        "title": "토목기사 취득 준비과정",
        "provider": "토목기술 교육원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "부산 동래",
        "summary": "토목기사 필기·실기 완벽 대비 과정입니다. 측량, 토질, 철근콘크리트를 다룹니다.",
        "target_audience": "토목기사 자격 취득 희망자",
        "skills": "측량 토질역학 철근콘크리트 수리학 상하수도",
        "benefits": "합격 보장반, 실기 집중 훈련",
        "schedule": "12주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-con-002",
        "ncs_code": "14", "ncs_name": "건설",
        "tags": ["토목기사", "측량", "철근콘크리트"],
    },
    {
        "title": "실내건축기능사 취득 과정",
        "provider": "인테리어 디자인 스쿨",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 강남",
        "summary": "실내건축기능사 취득을 위한 공간 설계, 재료, 도면 작성 실무를 배웁니다.",
        "target_audience": "인테리어 디자이너 지망생",
        "skills": "실내건축 공간설계 AutoCAD 재료학 시공",
        "benefits": "기능사 합격 보장, 포트폴리오 완성",
        "schedule": "10주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-con-003",
        "ncs_code": "14", "ncs_name": "건설",
        "tags": ["실내건축", "인테리어", "공간설계"],
    },
    {
        "title": "건설안전기사 취득 과정",
        "provider": "산업안전 교육원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "경기 수원",
        "summary": "건설안전기사 필기·실기 대비 과정입니다. 재해예방, 안전관리, 위험성평가를 배웁니다.",
        "target_audience": "건설 현장 안전관리 직무 희망자",
        "skills": "재해예방 안전관리 위험성평가 건설안전기준",
        "benefits": "합격 보장반, 기출 집중 풀이",
        "schedule": "8주 · 주 4일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-con-004",
        "ncs_code": "14", "ncs_name": "건설",
        "tags": ["건설안전기사", "안전관리", "건설"],
    },

    # ── 02 경영회계사무 (10개) ──────────────────────────────────────────────
    {
        "title": "전산회계 1급 취득 과정",
        "provider": "회계 직업훈련원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 중구",
        "summary": "KcLep 회계프로그램을 활용한 전산회계 1급 자격 취득 과정입니다.",
        "target_audience": "경리·회계 직무 취업 희망자",
        "skills": "전산회계 KcLep 분개 재무제표 부가세신고",
        "benefits": "전산회계 1급 합격 보장",
        "schedule": "6주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-biz-001",
        "ncs_code": "02", "ncs_name": "경영회계사무",
        "tags": ["전산회계", "회계", "KcLep", "경리"],
    },
    {
        "title": "ERP 회계·물류 실무 과정",
        "provider": "ERP 교육 센터",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 영등포",
        "summary": "SAP ERP, 더존 iCUBE를 활용한 회계, 구매, 물류 업무 처리 실무를 배웁니다.",
        "target_audience": "ERP 운용 직무 취업 희망자",
        "skills": "SAP ERP 더존iCUBE 회계 물류 구매",
        "benefits": "ERP 정보관리사 취득 지원",
        "schedule": "8주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-biz-002",
        "ncs_code": "02", "ncs_name": "경영회계사무",
        "tags": ["ERP", "SAP", "회계", "물류"],
    },
    {
        "title": "사무자동화산업기사 취득 과정",
        "provider": "IT자격증 아카데미",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "경기 의정부",
        "summary": "사무자동화산업기사 필기·실기 완벽 대비 과정입니다. 엑셀, 액세스, 파워포인트를 다룹니다.",
        "target_audience": "사무직 취업 및 자격증 취득 희망자",
        "skills": "엑셀 액세스 파워포인트 데이터베이스 사무자동화",
        "benefits": "합격 보장반",
        "schedule": "8주 · 주 4일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-biz-003",
        "ncs_code": "02", "ncs_name": "경영회계사무",
        "tags": ["사무자동화", "엑셀", "액세스", "자격증"],
    },
    {
        "title": "비즈니스 데이터 분석 과정",
        "provider": "경영분석 스쿨",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 강남",
        "summary": "Excel, Power BI, Python을 활용한 비즈니스 데이터 분석 및 시각화 실무를 배웁니다.",
        "target_audience": "마케터, 기획자, 경영 직군의 데이터 역량 강화",
        "skills": "Excel Power BI Python 데이터시각화 통계",
        "benefits": "실무 분석 프로젝트, 포트폴리오",
        "schedule": "8주 · 주 4일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-biz-004",
        "ncs_code": "02", "ncs_name": "경영회계사무",
        "tags": ["데이터분석", "Power BI", "Excel", "경영"],
    },
    {
        "title": "인사노무관리 실무 과정",
        "provider": "HR 전문 교육원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 마포",
        "summary": "채용, 급여, 4대보험, 노무관리 등 인사 담당자 핵심 업무를 실무 중심으로 배웁니다.",
        "target_audience": "인사 직무 취업 및 전환 희망자",
        "skills": "인사관리 급여계산 4대보험 노무 채용",
        "benefits": "인사실무사 자격증 취득 지원",
        "schedule": "6주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-biz-005",
        "ncs_code": "02", "ncs_name": "경영회계사무",
        "tags": ["인사", "노무", "HR", "급여"],
    },
    {
        "title": "마케팅·SNS 콘텐츠 운영 과정",
        "provider": "디지털 마케팅 스쿨",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 성동",
        "summary": "인스타그램, 유튜브, 네이버 블로그, 구글 애즈를 활용한 디지털 마케팅 실무를 배웁니다.",
        "target_audience": "마케터 지망생, 소상공인, SNS 운영 희망자",
        "skills": "SNS마케팅 콘텐츠기획 구글애즈 SEO 브랜딩",
        "benefits": "포트폴리오, 실제 캠페인 운영 경험",
        "schedule": "8주 · 주 3일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-biz-006",
        "ncs_code": "02", "ncs_name": "경영회계사무",
        "tags": ["마케팅", "SNS", "디지털마케팅", "콘텐츠"],
    },

    # ── 06 보건의료 (8개) ────────────────────────────────────────────────────
    {
        "title": "간호조무사 취업 준비과정",
        "provider": "보건의료 직업전문학교",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 중랑",
        "summary": "간호조무사 국가시험 준비와 병원·의원 취업을 위한 실무 교육 과정입니다.",
        "target_audience": "간호조무사 직무 전환 희망자",
        "skills": "기초간호 투약관리 병원행정 의료법규",
        "benefits": "국가시험 합격 보장반, 의원 취업 연계",
        "schedule": "16주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-med-001",
        "ncs_code": "06", "ncs_name": "보건의료",
        "tags": ["간호조무사", "보건의료", "국가시험"],
    },
    {
        "title": "요양보호사 양성 과정",
        "provider": "노인복지 교육원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "경기 고양",
        "summary": "요양보호사 국가자격증 취득을 위한 이론 및 실습 과정입니다.",
        "target_audience": "요양보호사 자격증 취득 희망자",
        "skills": "노인케어 신체활동지원 인지활동 의사소통",
        "benefits": "자격증 취득 후 즉시 취업 연계",
        "schedule": "6주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-med-002",
        "ncs_code": "06", "ncs_name": "보건의료",
        "tags": ["요양보호사", "노인복지", "자격증"],
    },
    {
        "title": "의료코딩·건강보험 청구 실무 과정",
        "provider": "보건행정 교육원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 구로",
        "summary": "KCD 진단코드, 건강보험 청구, EDI 청구 방법을 실무 중심으로 배웁니다.",
        "target_audience": "의무기록사, 원무행정 직무 희망자",
        "skills": "KCD진단코드 건강보험청구 EDI 원무행정",
        "benefits": "의무기록사 자격 취득 지원",
        "schedule": "8주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-med-003",
        "ncs_code": "06", "ncs_name": "보건의료",
        "tags": ["의무기록", "보험청구", "보건행정"],
    },

    # ── 07 사회복지종교 (5개) ───────────────────────────────────────────────
    {
        "title": "사회복지사 2급 취득 과정",
        "provider": "사회복지 아카데미",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 노원",
        "summary": "사회복지사 2급 자격 취득을 위한 이론 교육 및 실습 연계 과정입니다.",
        "target_audience": "사회복지 직무 전환 및 신규 희망자",
        "skills": "사회복지 케이스워크 지역사회조직 사례관리",
        "benefits": "실습기관 연계, 취업 지원",
        "schedule": "12주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-soc-001",
        "ncs_code": "07", "ncs_name": "사회복지종교",
        "tags": ["사회복지사", "복지", "자격증"],
    },
    {
        "title": "보육교사 자격 과정",
        "provider": "아동보육 교육원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 강서",
        "summary": "보육교사 2급 자격 취득을 위한 아동발달, 놀이지도, 영유아 보육 과정입니다.",
        "target_audience": "보육교사 직무 희망자",
        "skills": "아동발달 놀이지도 영유아보육 부모상담",
        "benefits": "어린이집 취업 연계",
        "schedule": "12주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-soc-002",
        "ncs_code": "07", "ncs_name": "사회복지종교",
        "tags": ["보육교사", "아동보육", "유아교육"],
    },

    # ── 13 음식서비스 (5개) ─────────────────────────────────────────────────
    {
        "title": "한식조리기능사 취득 과정",
        "provider": "조리직업전문학교",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 중구",
        "summary": "한식조리기능사 실기 집중 훈련 과정입니다. 한식 50가지 메뉴 실습을 진행합니다.",
        "target_audience": "조리 직무 취업 및 창업 희망자",
        "skills": "한식조리 식재료관리 위생관리 조리원리",
        "benefits": "기능사 합격 보장, 외식업체 취업 연계",
        "schedule": "8주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-food-001",
        "ncs_code": "13", "ncs_name": "음식서비스",
        "tags": ["한식조리", "조리기능사", "요리"],
    },
    {
        "title": "바리스타·카페 창업 과정",
        "provider": "커피 아카데미",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 마포",
        "summary": "에스프레소 추출, 라떼아트, 원두 선별, 카페 운영 관리까지 바리스타 전 과정을 배웁니다.",
        "target_audience": "카페 취업 및 창업 희망자",
        "skills": "에스프레소 라떼아트 원두로스팅 카페운영 음료레시피",
        "benefits": "바리스타 2급 자격증 취득 지원",
        "schedule": "6주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-food-002",
        "ncs_code": "13", "ncs_name": "음식서비스",
        "tags": ["바리스타", "카페", "커피", "창업"],
    },
    {
        "title": "양식조리기능사 취득 과정",
        "provider": "조리직업전문학교",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "경기 성남",
        "summary": "양식조리기능사 실기 시험에 출제되는 메뉴를 집중 훈련합니다.",
        "target_audience": "호텔·레스토랑 양식 조리사 지망생",
        "skills": "양식조리 소스제조 플레이팅 식재료관리",
        "benefits": "기능사 합격 보장, 호텔 취업 연계",
        "schedule": "8주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-food-003",
        "ncs_code": "13", "ncs_name": "음식서비스",
        "tags": ["양식조리", "조리기능사", "호텔"],
    },

    # ── 03 금융보험 (5개) ───────────────────────────────────────────────────
    {
        "title": "금융투자분석사 취득 과정",
        "provider": "금융 자격 아카데미",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 여의도",
        "summary": "증권, 채권, 파생상품 분석 역량을 기르고 금융투자분석사 자격을 취득합니다.",
        "target_audience": "증권사·자산운용사 취업 희망자",
        "skills": "주식분석 채권분석 파생상품 재무분석 포트폴리오",
        "benefits": "자격증 취득 지원, 증권사 채용 연계",
        "schedule": "10주 · 주 4일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-fin-001",
        "ncs_code": "03", "ncs_name": "금융보험",
        "tags": ["금융투자", "증권", "자격증", "CFA"],
    },
    {
        "title": "손해사정사 취득 준비과정",
        "provider": "보험 전문 교육원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 강남",
        "summary": "손해사정사 필기·실기 대비 과정으로 보험법, 약관, 손해 산정 방법을 다룹니다.",
        "target_audience": "보험사·손해사정 직무 희망자",
        "skills": "보험법 손해사정 약관분석 재보험 보험계리",
        "benefits": "자격증 취득 지원, 보험사 채용 연계",
        "schedule": "12주 · 주 4일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-fin-002",
        "ncs_code": "03", "ncs_name": "금융보험",
        "tags": ["손해사정사", "보험", "자격증"],
    },

    # ── 23 환경에너지안전 (5개) ─────────────────────────────────────────────
    {
        "title": "산업안전기사 취득 과정",
        "provider": "산업안전 전문 교육원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "경기 안양",
        "summary": "산업안전기사 필기·실기 완벽 대비 과정입니다. 재해예방, 위험성평가, 안전관리를 배웁니다.",
        "target_audience": "산업 현장 안전관리 직무 희망자",
        "skills": "재해예방 위험성평가 안전관리 보호구 법규",
        "benefits": "합격 보장반, 기출 집중 풀이",
        "schedule": "10주 · 주 4일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-env-001",
        "ncs_code": "23", "ncs_name": "환경에너지안전",
        "tags": ["산업안전기사", "안전관리", "자격증"],
    },
    {
        "title": "에너지관리기사 취득 과정",
        "provider": "에너지 기술 아카데미",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "경기 수원",
        "summary": "에너지관리기사 필기·실기 대비 과정으로 열역학, 보일러, 에너지 절감을 다룹니다.",
        "target_audience": "에너지 관련 시설 관리 직무 희망자",
        "skills": "열역학 보일러 냉동 에너지절감 유체역학",
        "benefits": "기사 합격 보장반",
        "schedule": "10주 · 주 4일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-env-002",
        "ncs_code": "23", "ncs_name": "환경에너지안전",
        "tags": ["에너지관리기사", "보일러", "에너지"],
    },
    {
        "title": "환경기사 취득 준비과정",
        "provider": "환경 전문 교육원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 관악",
        "summary": "환경기사 필기·실기 대비 과정입니다. 수질, 대기, 폐기물 처리, 소음 분야를 다룹니다.",
        "target_audience": "환경 직무 취업 및 자격 취득 희망자",
        "skills": "수질오염 대기오염 폐기물처리 소음진동 환경법규",
        "benefits": "합격 보장반",
        "schedule": "12주 · 주 4일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-env-003",
        "ncs_code": "23", "ncs_name": "환경에너지안전",
        "tags": ["환경기사", "수질", "대기", "환경"],
    },

    # ── 취업역량 강화 프로그램 (15개) ──────────────────────────────────────
    {
        "title": "AI 개발자 취업 포트폴리오 완성 프로그램",
        "provider": "고용24 연계 취업지원",
        "program_type": "capability",
        "category": "구직자취업역량 강화프로그램",
        "location": "온라인",
        "summary": "프로젝트 정리, 기술 스택 스토리텔링, 면접 답변 구조화로 AI·백엔드 개발자 포트폴리오를 완성합니다.",
        "target_audience": "AI·개발 직무 포트폴리오가 필요한 구직자",
        "skills": "포트폴리오 자소서 면접 스토리텔링",
        "benefits": "1:1 피드백, 자소서 첨삭, 모의면접",
        "schedule": "3주 · 주 2회", "tuition": "무료", "url": "",
        "source": "sample", "external_id": "s-cap-001",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["포트폴리오", "AI개발자", "면접", "취업"],
    },
    {
        "title": "청년 구직자 면접 역량 강화 프로그램",
        "provider": "고용센터 취업지원팀",
        "program_type": "capability",
        "category": "구직자취업역량 강화프로그램",
        "location": "전국 고용센터",
        "summary": "자기소개서 작성, 모의면접, 직무분석, 지원전략 수립을 통해 구직 성공률을 높입니다.",
        "target_audience": "취업에 어려움을 겪는 청년 구직자",
        "skills": "자소서 면접 직무분석 이미지메이킹",
        "benefits": "1:1 컨설팅, 모의면접, 첨삭 서비스",
        "schedule": "2주 · 주 3회", "tuition": "무료", "url": "",
        "source": "sample", "external_id": "s-cap-002",
        "ncs_code": "02", "ncs_name": "경영회계사무",
        "tags": ["면접", "자소서", "취업전략", "청년"],
    },
    {
        "title": "제조업 현장직 취업 역량 강화",
        "provider": "고용센터 취업지원팀",
        "program_type": "capability",
        "category": "구직자취업역량 강화프로그램",
        "location": "경기 안산",
        "summary": "제조업 현장직 취업에 필요한 안전교육, 기초 기술, 이력서 작성법을 배웁니다.",
        "target_audience": "제조업 생산직 취업 희망자",
        "skills": "산업안전 이력서작성 면접준비 현장소통",
        "benefits": "제조업체 취업 연계",
        "schedule": "1주 · 주 5일", "tuition": "무료", "url": "",
        "source": "sample", "external_id": "s-cap-003",
        "ncs_code": "15", "ncs_name": "기계",
        "tags": ["제조업", "현장직", "취업", "안전"],
    },
    {
        "title": "중장년 재취업 역량 강화 프로그램",
        "provider": "고용센터 중장년 지원팀",
        "program_type": "capability",
        "category": "구직자취업역량 강화프로그램",
        "location": "서울 종로",
        "summary": "50대 이상 구직자의 이력서 재정비, 경력 정리, 희망 직종 탐색을 지원합니다.",
        "target_audience": "재취업을 준비하는 중장년 구직자",
        "skills": "경력정리 이력서 면접준비 직종탐색",
        "benefits": "커리어 컨설팅, 직종 전환 지원",
        "schedule": "2주 · 주 3회", "tuition": "무료", "url": "",
        "source": "sample", "external_id": "s-cap-004",
        "ncs_code": "02", "ncs_name": "경영회계사무",
        "tags": ["중장년", "재취업", "50대", "경력"],
    },
    {
        "title": "여성 경력단절 재취업 지원 프로그램",
        "provider": "여성새로일하기센터",
        "program_type": "capability",
        "category": "구직자취업역량 강화프로그램",
        "location": "전국",
        "summary": "경력단절 여성의 취업 의욕 고취, 직종 탐색, 이력서 작성, 면접 준비를 돕습니다.",
        "target_audience": "경력단절 후 재취업을 원하는 여성",
        "skills": "직종탐색 이력서 면접 경력환산",
        "benefits": "1:1 취업상담, 훈련과정 연계",
        "schedule": "3주 · 주 3회", "tuition": "무료", "url": "",
        "source": "sample", "external_id": "s-cap-005",
        "ncs_code": "07", "ncs_name": "사회복지종교",
        "tags": ["여성재취업", "경력단절", "취업지원"],
    },

    # ── 일학습병행 과정 (10개) ──────────────────────────────────────────────
    {
        "title": "클라우드 네이티브 엔지니어 일학습병행",
        "provider": "일학습병행 운영기관",
        "program_type": "apprenticeship",
        "category": "일학습병행훈련과정",
        "location": "경기 성남",
        "summary": "기업 현장 실무와 병행해 Docker, Kubernetes, CI/CD 기반 클라우드 운영 역량을 쌓습니다.",
        "target_audience": "현장 실무와 교육을 동시에 원하는 취업 준비생",
        "skills": "Docker Kubernetes AWS CI/CD Linux",
        "benefits": "현장 실무 경험, 훈련수당, 취업 연계",
        "schedule": "16주 · 기업 실습 병행", "tuition": "기업연계 지원", "url": "",
        "source": "sample", "external_id": "s-app-001",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["클라우드", "Kubernetes", "일학습병행"],
    },
    {
        "title": "스마트공장 운용 일학습병행",
        "provider": "스마트제조 일학습병행 훈련원",
        "program_type": "apprenticeship",
        "category": "일학습병행훈련과정",
        "location": "경남 창원",
        "summary": "스마트공장 MES, PLC, 산업용 IoT 운용 능력을 기업 실습과 함께 배웁니다.",
        "target_audience": "스마트 제조 현장 기술직 희망자",
        "skills": "MES PLC IoT 자동화 데이터수집",
        "benefits": "현장 실무, 훈련수당, 스마트공장 기업 취업",
        "schedule": "20주 · 기업 실습 병행", "tuition": "기업연계 지원", "url": "",
        "source": "sample", "external_id": "s-app-002",
        "ncs_code": "15", "ncs_name": "기계",
        "tags": ["스마트공장", "PLC", "일학습병행", "제조"],
    },
    {
        "title": "건축 인테리어 시공 일학습병행",
        "provider": "건축 일학습 훈련기관",
        "program_type": "apprenticeship",
        "category": "일학습병행훈련과정",
        "location": "서울 성동",
        "summary": "인테리어 현장 시공, 도면 해독, 자재 관리를 기업 실습과 함께 익힙니다.",
        "target_audience": "인테리어 시공 직무 희망자",
        "skills": "시공관리 도면해독 자재관리 현장관리",
        "benefits": "현장 경력 취득, 훈련수당",
        "schedule": "24주 · 기업 실습 병행", "tuition": "기업연계 지원", "url": "",
        "source": "sample", "external_id": "s-app-003",
        "ncs_code": "14", "ncs_name": "건설",
        "tags": ["인테리어", "시공", "일학습병행", "건설"],
    },

    # ── 추가 ICT 과정 (완성도) ──────────────────────────────────────────────
    {
        "title": "Java Spring Boot 백엔드 개발 과정",
        "provider": "자바 개발 아카데미",
        "program_type": "kdt",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 종로",
        "summary": "Java, Spring Boot, JPA, MySQL을 활용한 기업용 백엔드 서비스 개발을 배웁니다.",
        "target_audience": "Java 백엔드 개발자 지망생",
        "skills": "Java Spring Boot JPA MySQL REST API",
        "benefits": "기업 프로젝트, 코드 리뷰, 취업 연계",
        "schedule": "16주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-ict-016",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["Java", "Spring Boot", "백엔드", "JPA"],
    },
    {
        "title": "Vue.js·React 프론트엔드 개발 과정",
        "provider": "프론트엔드 스쿨",
        "program_type": "kdt",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 강남",
        "summary": "Vue.js와 React를 모두 다루는 프론트엔드 개발 과정입니다. TypeScript, 상태관리도 포함합니다.",
        "target_audience": "프론트엔드 개발자 지망생",
        "skills": "Vue.js React TypeScript JavaScript CSS",
        "benefits": "포트폴리오 완성, 취업 연계",
        "schedule": "14주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-ict-017",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["Vue.js", "React", "프론트엔드", "TypeScript"],
    },
    {
        "title": "빅데이터 분석기사 취득 과정",
        "provider": "빅데이터 아카데미",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 강남",
        "summary": "빅데이터 분석기사 필기·실기 완벽 대비 과정입니다. 파이썬 분석, 시각화, 머신러닝을 다룹니다.",
        "target_audience": "데이터 분석 자격증 취득 희망자",
        "skills": "Python 통계 머신러닝 데이터시각화 R",
        "benefits": "합격 보장반, 1:1 피드백",
        "schedule": "8주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-ict-018",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["빅데이터분석기사", "데이터분석", "Python"],
    },
    {
        "title": "AWS Solutions Architect 자격 과정",
        "provider": "클라우드 자격증 스쿨",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "온라인",
        "summary": "AWS SAA-C03 시험 대비 과정으로 EC2, S3, VPC, RDS 등 AWS 핵심 서비스를 배웁니다.",
        "target_audience": "AWS 자격증 취득 및 클라우드 엔지니어 직무 희망자",
        "skills": "AWS EC2 S3 VPC RDS Lambda CloudFormation",
        "benefits": "AWS 바우처 제공, 시험 응시 지원",
        "schedule": "6주 · 주 4일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-ict-019",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["AWS", "클라우드", "자격증", "SAA"],
    },
    {
        "title": "DevOps 엔지니어 양성과정",
        "provider": "DevOps 부트캠프",
        "program_type": "kdt",
        "category": "국민내일배움카드 훈련과정",
        "location": "경기 판교",
        "summary": "Jenkins, GitLab CI/CD, Ansible, Prometheus, Grafana를 활용한 DevOps 실무를 배웁니다.",
        "target_audience": "DevOps 엔지니어 전환 희망자",
        "skills": "Jenkins GitLab CI/CD Ansible Kubernetes Prometheus",
        "benefits": "포트폴리오, IT 기업 채용 연계",
        "schedule": "12주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-ict-020",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["DevOps", "CI/CD", "Jenkins", "Kubernetes"],
    },

    # ── 16 재료 / 17 화학 ───────────────────────────────────────────────────
    {
        "title": "화학분석기사 취득 과정",
        "provider": "화학 기술 교육원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "전남 여수",
        "summary": "화학분석기사 필기·실기 대비 과정으로 화학 분석, 기기 분석, 품질 관리를 배웁니다.",
        "target_audience": "화학 제조·연구 직무 희망자",
        "skills": "화학분석 기기분석 품질관리 시험법 GC HPLC",
        "benefits": "기사 합격 보장반",
        "schedule": "10주 · 주 4일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-chem-001",
        "ncs_code": "17", "ncs_name": "화학",
        "tags": ["화학분석기사", "화학", "품질관리"],
    },
    {
        "title": "금속재료기사 취득 과정",
        "provider": "재료 기술 아카데미",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "경북 포항",
        "summary": "금속재료기사 필기·실기 준비 과정으로 금속학, 열처리, 재료시험을 다룹니다.",
        "target_audience": "철강·금속 제조 직무 희망자",
        "skills": "금속학 열처리 재료시험 비파괴검사 야금",
        "benefits": "포스코·현대제철 채용 연계",
        "schedule": "10주 · 주 4일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-mat-001",
        "ncs_code": "16", "ncs_name": "재료",
        "tags": ["금속재료기사", "금속", "철강", "재료"],
    },

    # ── 08 문화예술디자인방송 ───────────────────────────────────────────────
    {
        "title": "영상편집·유튜브 크리에이터 과정",
        "provider": "미디어 아카데미",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 마포",
        "summary": "Premiere Pro, After Effects, DaVinci Resolve를 활용한 영상 편집 및 유튜브 채널 운영을 배웁니다.",
        "target_audience": "영상 크리에이터, 영상편집 직무 희망자",
        "skills": "Premiere Pro After Effects DaVinci 영상촬영 유튜브",
        "benefits": "채널 개설 및 영상 제작 지원",
        "schedule": "8주 · 주 4일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-art-001",
        "ncs_code": "08", "ncs_name": "문화예술디자인방송",
        "tags": ["영상편집", "유튜브", "Premiere Pro", "크리에이터"],
    },
    {
        "title": "3D 프린팅·제품 디자인 과정",
        "provider": "메이커스 스쿨",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 노원",
        "summary": "Fusion 360, Rhino를 이용한 3D 모델링과 FDM·SLA 3D 프린팅 실무를 배웁니다.",
        "target_audience": "제품 디자이너, 메이커 직무 희망자",
        "skills": "Fusion360 Rhino 3D프린팅 제품설계 목업",
        "benefits": "3D 프린팅 운용기능사 취득 지원",
        "schedule": "8주 · 주 4일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-art-002",
        "ncs_code": "08", "ncs_name": "문화예술디자인방송",
        "tags": ["3D프린팅", "제품디자인", "Fusion360"],
    },

    # ── 21 식품가공 ─────────────────────────────────────────────────────────
    {
        "title": "식품기사 취득 준비과정",
        "provider": "식품 전문 교육원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "경기 광주",
        "summary": "식품기사 필기·실기 대비 과정으로 식품화학, 미생물, 위생법규를 배웁니다.",
        "target_audience": "식품 제조·QC 직무 희망자",
        "skills": "식품화학 식품미생물 식품가공 위생법규 품질관리",
        "benefits": "합격 보장반",
        "schedule": "10주 · 주 4일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-food2-001",
        "ncs_code": "21", "ncs_name": "식품가공",
        "tags": ["식품기사", "식품", "위생", "품질관리"],
    },

    # ── 10 영업판매 ─────────────────────────────────────────────────────────
    {
        "title": "B2B 세일즈 실무 과정",
        "provider": "영업 전문 교육원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 중구",
        "summary": "B2B 영업 프로세스, 협상 스킬, CRM 활용, 제안서 작성을 체계적으로 배웁니다.",
        "target_audience": "영업·세일즈 직무 전환 및 신규 희망자",
        "skills": "영업전략 협상 CRM 제안서작성 고객관리",
        "benefits": "모의 영업 실습, 기업 현장 방문",
        "schedule": "4주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-sale-001",
        "ncs_code": "10", "ncs_name": "영업판매",
        "tags": ["B2B영업", "세일즈", "CRM", "협상"],
    },
    {
        "title": "이커머스·쇼핑몰 창업 운영 과정",
        "provider": "이커머스 교육원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 성동",
        "summary": "스마트스토어, 쿠팡, 배민 입점, 상품 소싱, 광고 운영까지 이커머스 전 과정을 배웁니다.",
        "target_audience": "온라인 쇼핑몰 창업 및 이커머스 직무 희망자",
        "skills": "스마트스토어 상품소싱 광고운영 CS 물류관리",
        "benefits": "실제 쇼핑몰 운영 실습, 창업 멘토링",
        "schedule": "6주 · 주 4일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-sale-002",
        "ncs_code": "10", "ncs_name": "영업판매",
        "tags": ["이커머스", "스마트스토어", "쇼핑몰창업", "온라인판매"],
    },

    # ── 24 농림어업 ─────────────────────────────────────────────────────────
    {
        "title": "스마트팜 운용 과정",
        "provider": "농업기술센터",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "전북 완주",
        "summary": "ICT 기반 스마트 온실 제어, 데이터 기반 작물 관리, 스마트팜 창업을 배웁니다.",
        "target_audience": "스마트팜 창업 및 농업 직무 희망자",
        "skills": "스마트팜 온실제어 IoT 작물재배 농업경영",
        "benefits": "스마트팜 실습 시설, 창업 지원",
        "schedule": "8주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-agr-001",
        "ncs_code": "24", "ncs_name": "농림어업",
        "tags": ["스마트팜", "농업", "IoT", "창업"],
    },

    # ── 추가 취업역량 강화 ───────────────────────────────────────────────────
    {
        "title": "이공계 대학원생 취업역량 강화",
        "provider": "청년취업아카데미",
        "program_type": "capability",
        "category": "구직자취업역량 강화프로그램",
        "location": "대전 유성",
        "summary": "연구 역량을 산업계 직무로 연결하는 이공계 특화 취업 프로그램입니다.",
        "target_audience": "이공계 대학원 수료 및 졸업 예정자",
        "skills": "기술면접 특허전략 R&D직무 이직전략",
        "benefits": "연구소·기업 R&D 채용 연계",
        "schedule": "3주 · 주 3회", "tuition": "무료", "url": "",
        "source": "sample", "external_id": "s-cap-006",
        "ncs_code": "04", "ncs_name": "교육자연사회과학",
        "tags": ["이공계", "대학원", "R&D", "기술면접"],
    },
    {
        "title": "디자이너·크리에이터 포트폴리오 클리닉",
        "provider": "창의인재개발원",
        "program_type": "capability",
        "category": "구직자취업역량 강화프로그램",
        "location": "서울 마포",
        "summary": "디자이너와 크리에이터가 자신의 작업을 효과적으로 보여주는 포트폴리오 구성법을 배웁니다.",
        "target_audience": "디자인·미디어 직무 취업 희망자",
        "skills": "포트폴리오 브랜딩 자소서 면접 작품선별",
        "benefits": "현업 디자이너 1:1 피드백",
        "schedule": "2주 · 주 2회", "tuition": "무료", "url": "",
        "source": "sample", "external_id": "s-cap-007",
        "ncs_code": "08", "ncs_name": "문화예술디자인방송",
        "tags": ["디자이너", "포트폴리오", "크리에이터", "면접"],
    },
    {
        "title": "복지 직무 취업 연계 프로그램",
        "provider": "사회서비스원",
        "program_type": "capability",
        "category": "구직자취업역량 강화프로그램",
        "location": "경기 수원",
        "summary": "사회복지관·노인요양시설 취업을 위한 직무교육과 현장 실습을 병행합니다.",
        "target_audience": "사회복지 직무 취업 희망자",
        "skills": "사례관리 노인복지 이력서 면접 현장실습",
        "benefits": "복지기관 취업 직결 연계",
        "schedule": "3주 · 주 5일", "tuition": "무료", "url": "",
        "source": "sample", "external_id": "s-cap-008",
        "ncs_code": "07", "ncs_name": "사회복지종교",
        "tags": ["사회복지", "요양", "취업연계", "복지"],
    },
    {
        "title": "전기·기계 직종 자격증 취업 패키지",
        "provider": "고용센터 기술직 취업팀",
        "program_type": "capability",
        "category": "구직자취업역량 강화프로그램",
        "location": "인천 남동",
        "summary": "전기·기계 기능사 취득 후 제조·설비 업체 취업을 연계하는 패키지 프로그램입니다.",
        "target_audience": "기술직 전환을 희망하는 구직자",
        "skills": "전기기능사 기계가공 이력서 면접",
        "benefits": "자격증 취득 → 즉시 취업 연계",
        "schedule": "4주 · 주 5일", "tuition": "무료", "url": "",
        "source": "sample", "external_id": "s-cap-009",
        "ncs_code": "19", "ncs_name": "전기전자",
        "tags": ["전기", "기계", "자격증", "기술직취업"],
    },
    {
        "title": "IT 비전공자 개발자 전환 부트캠프",
        "provider": "코드스테이츠",
        "program_type": "kdt",
        "category": "국민내일배움카드 훈련과정",
        "location": "온라인",
        "summary": "코딩을 처음 시작하는 비전공자도 6개월 안에 주니어 개발자로 취업할 수 있도록 커리큘럼을 설계했습니다.",
        "target_audience": "IT 비전공자, 개발자 직무 전환 희망자",
        "skills": "JavaScript React Node.js 알고리즘 자료구조",
        "benefits": "취업 전 무료, 취업 후 소득 공유",
        "schedule": "24주 · 주 5일", "tuition": "취업 후 납부", "url": "",
        "source": "sample", "external_id": "s-ict-021",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["비전공자", "개발자전환", "JavaScript", "부트캠프"],
    },
    {
        "title": "의료기기 규제과학 실무 과정",
        "provider": "식약처 인증 교육기관",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 서초",
        "summary": "의료기기 인허가, GMP, 임상시험, 경제성평가 등 규제 실무 역량을 기릅니다.",
        "target_audience": "의료기기 기업 RA·QA 직무 희망자",
        "skills": "GMP 인허가 RA QA 임상시험 의료기기법",
        "benefits": "의료기기 기업 취업 연계",
        "schedule": "8주 · 주 4일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-med-004",
        "ncs_code": "06", "ncs_name": "보건의료",
        "tags": ["의료기기", "GMP", "RA", "규제과학"],
    },
    {
        "title": "건강기능식품 QC 실무 과정",
        "provider": "식품안전 교육원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "경기 오산",
        "summary": "건강기능식품 제조 현장에서 요구하는 품질관리, 미생물 검사, 분석 실무를 배웁니다.",
        "target_audience": "건강기능식품 QC 직무 희망자",
        "skills": "품질관리 미생물검사 이화학분석 GMP 식품법규",
        "benefits": "식품회사 QC 취업 연계",
        "schedule": "8주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-food2-002",
        "ncs_code": "21", "ncs_name": "식품가공",
        "tags": ["건강기능식품", "QC", "품질관리", "식품"],
    },
    {
        "title": "소방설비기사 취득 과정",
        "provider": "소방 전문 교육원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "경기 이천",
        "summary": "소방설비기사 필기·실기 대비 과정으로 소화설비, 경보설비, 피난설비를 배웁니다.",
        "target_audience": "소방설비 시공·감리 직무 희망자",
        "skills": "소화설비 경보설비 피난설비 소방법규 도면해독",
        "benefits": "합격 보장반",
        "schedule": "10주 · 주 4일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-env-004",
        "ncs_code": "23", "ncs_name": "환경에너지안전",
        "tags": ["소방설비기사", "소방", "설비", "자격증"],
    },
    {
        "title": "플랜트 배관 설계 과정",
        "provider": "플랜트 교육원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "경남 거제",
        "summary": "플랜트 배관 설계, 등각도, CAESAR II 해석 능력을 기르는 전문 과정입니다.",
        "target_audience": "플랜트·조선 배관 직무 희망자",
        "skills": "배관설계 등각도 CAESARII AutoCAD 플랜트배관",
        "benefits": "조선소·플랜트 기업 채용 연계",
        "schedule": "12주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-mec-006",
        "ncs_code": "15", "ncs_name": "기계",
        "tags": ["플랜트", "배관설계", "조선", "CAESARII"],
    },
    {
        "title": "패션 MD·바잉 실무 과정",
        "provider": "패션 비즈니스 스쿨",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 동대문",
        "summary": "패션 MD의 시즌 기획, 소싱, 바잉, 재고 관리 전 과정을 배우는 실무 중심 과정입니다.",
        "target_audience": "패션 MD·바잉 직무 희망자",
        "skills": "MD기획 소싱 바잉 재고관리 트렌드분석",
        "benefits": "패션 기업 취업 연계, 현장 실습",
        "schedule": "8주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-tex-001",
        "ncs_code": "18", "ncs_name": "섬유의복",
        "tags": ["패션MD", "바잉", "패션", "소싱"],
    },
    {
        "title": "물류관리사 취득 과정",
        "provider": "물류 전문 교육원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "인천 연수",
        "summary": "물류관리사 시험 대비 과정으로 화물운송, 보관하역, 국제물류를 배웁니다.",
        "target_audience": "물류·유통 직무 취업 및 자격증 취득 희망자",
        "skills": "화물운송 보관하역 국제물류 공급망관리 관세",
        "benefits": "합격 보장반, 물류기업 채용 연계",
        "schedule": "8주 · 주 4일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-trans-001",
        "ncs_code": "09", "ncs_name": "운전운송",
        "tags": ["물류관리사", "물류", "자격증", "공급망"],
    },
]


def seed_sample_programs(db) -> int:
    """샘플 훈련과정을 DB에 시딩합니다. 이미 있는 항목은 건너뜁니다."""
    return program_repo.upsert_many(db, SAMPLE_PROGRAMS)

# ── 추가 20개 (총 100개) ────────────────────────────────────────────────────
SAMPLE_PROGRAMS += [
    {
        "title": "광고기획·카피라이팅 실무 과정",
        "provider": "광고 크리에이티브 스쿨",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 강남",
        "summary": "ATL/BTL 광고 기획, 카피라이팅, 브랜드 전략을 실무 프로젝트 중심으로 배웁니다.",
        "target_audience": "광고·마케팅 직무 희망자",
        "skills": "광고기획 카피라이팅 브랜드전략 ATL BTL",
        "benefits": "광고 포트폴리오, 기업 연계",
        "schedule": "8주 · 주 4일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-art-003",
        "ncs_code": "08", "ncs_name": "문화예술디자인방송",
        "tags": ["광고기획", "카피라이팅", "마케팅", "브랜드"],
    },
    {
        "title": "전산세무 2급 취득 과정",
        "provider": "세무회계 직업훈련원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 용산",
        "summary": "전산세무 2급 자격 취득을 위한 부가세, 원천세, 법인세 신고 실무를 배웁니다.",
        "target_audience": "세무 직무 취업 및 자격증 취득 희망자",
        "skills": "부가세 원천세 법인세 KcLep세무 회계",
        "benefits": "전산세무 2급 합격 보장",
        "schedule": "8주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-biz-007",
        "ncs_code": "02", "ncs_name": "경영회계사무",
        "tags": ["전산세무", "세무", "회계", "자격증"],
    },
    {
        "title": "Python 데이터 사이언스 입문 과정",
        "provider": "데이터사이언스 스쿨",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "온라인",
        "summary": "Python 기초부터 Pandas, Matplotlib, scikit-learn까지 데이터 사이언스 입문 전 과정을 다룹니다.",
        "target_audience": "데이터 직무 입문자, 비전공자",
        "skills": "Python Pandas NumPy Matplotlib scikit-learn",
        "benefits": "프로젝트 포트폴리오, 1:1 멘토링",
        "schedule": "10주 · 주 4일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-ict-022",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["Python", "데이터사이언스", "머신러닝", "입문"],
    },
    {
        "title": "냉동·냉장 설비 기능사 취득 과정",
        "provider": "냉동기계 교육원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "경기 시흥",
        "summary": "냉동기계기능사 실기 집중 훈련 과정입니다. 냉동 사이클, 배관, 충전 작업을 배웁니다.",
        "target_audience": "냉동·공조 설비 기술직 희망자",
        "skills": "냉동사이클 배관작업 냉매충전 설비점검",
        "benefits": "냉동기계기능사 합격 보장",
        "schedule": "8주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-mec-007",
        "ncs_code": "15", "ncs_name": "기계",
        "tags": ["냉동기계", "냉동설비", "기능사"],
    },
    {
        "title": "무역영어·무역실무 과정",
        "provider": "무역 전문 교육원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 강남",
        "summary": "수출입 절차, 무역 영어 작문, 신용장, 인코텀즈, 관세 실무를 배웁니다.",
        "target_audience": "무역·물류 직무 취업 희망자",
        "skills": "무역영어 LC 인코텀즈 관세 수출입통관",
        "benefits": "무역영어 1급 취득 지원",
        "schedule": "8주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-biz-008",
        "ncs_code": "02", "ncs_name": "경영회계사무",
        "tags": ["무역영어", "무역실무", "수출입", "관세"],
    },
    {
        "title": "조경기사 취득 준비과정",
        "provider": "조경 전문 교육원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "경기 고양",
        "summary": "조경기사 필기·실기 대비 과정으로 조경계획, 식재, 시공, 포장을 배웁니다.",
        "target_audience": "조경 설계·시공 직무 희망자",
        "skills": "조경계획 식재설계 시공관리 포장설계 유지관리",
        "benefits": "합격 보장반",
        "schedule": "10주 · 주 4일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-con-005",
        "ncs_code": "14", "ncs_name": "건설",
        "tags": ["조경기사", "조경", "설계", "시공"],
    },
    {
        "title": "GIS·공간정보 분석 과정",
        "provider": "공간정보 교육원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "대전 유성",
        "summary": "ArcGIS, QGIS를 활용한 공간 데이터 수집, 분석, 시각화 실무를 배웁니다.",
        "target_audience": "GIS 분석가, 공간정보 직무 희망자",
        "skills": "ArcGIS QGIS Python공간분석 원격탐사 지형도",
        "benefits": "공간정보처리기사 취득 지원",
        "schedule": "10주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-ict-023",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["GIS", "ArcGIS", "공간정보", "QGIS"],
    },
    {
        "title": "특수용접 기능사 취득 과정",
        "provider": "용접 직업훈련원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "경남 거제",
        "summary": "TIG·MIG 특수용접 실기 심화 과정으로 선박·플랜트 현장 취업을 목표로 합니다.",
        "target_audience": "조선·플랜트 특수용접사 희망자",
        "skills": "TIG용접 MIG용접 스테인리스 알루미늄 비파괴",
        "benefits": "조선소·플랜트 취업 직결 연계",
        "schedule": "10주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-mec-008",
        "ncs_code": "15", "ncs_name": "기계",
        "tags": ["특수용접", "TIG", "조선", "플랜트"],
    },
    {
        "title": "창업 아이디어 검증·MVP 개발 과정",
        "provider": "스타트업 아카데미",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 성동",
        "summary": "창업 아이디어 검증부터 린스타트업, MVP 개발, 투자 유치 준비까지 창업 전 과정을 다룹니다.",
        "target_audience": "예비창업자, 스타트업 직무 희망자",
        "skills": "린스타트업 MVP 비즈니스모델 투자유치 IR피치",
        "benefits": "창업 멘토링, 액셀러레이터 연계",
        "schedule": "8주 · 주 3일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-biz-009",
        "ncs_code": "01", "ncs_name": "사업관리",
        "tags": ["창업", "스타트업", "MVP", "IR"],
    },
    {
        "title": "PM·서비스 기획자 양성과정",
        "provider": "프로덕트 스쿨",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 강남",
        "summary": "요구사항 정의, 기획서 작성, 데이터 기반 의사결정, 애자일·스크럼 방법론을 배웁니다.",
        "target_audience": "IT 서비스 기획자, PM 직무 전환 희망자",
        "skills": "서비스기획 PRD 애자일 스크럼 데이터분석 Jira",
        "benefits": "포트폴리오, IT 기업 기획팀 연계",
        "schedule": "10주 · 주 4일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-biz-010",
        "ncs_code": "01", "ncs_name": "사업관리",
        "tags": ["PM", "서비스기획", "애자일", "프로덕트"],
    },
    {
        "title": "Kotlin 안드로이드 앱 개발 과정",
        "provider": "모바일 개발 아카데미",
        "program_type": "kdt",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 구로",
        "summary": "Kotlin과 Android Studio를 이용한 네이티브 안드로이드 앱 개발 실무 과정입니다.",
        "target_audience": "안드로이드 개발자 지망생",
        "skills": "Kotlin Android Studio Jetpack Compose Firebase Room",
        "benefits": "앱스토어 출시, 포트폴리오 완성",
        "schedule": "12주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-ict-024",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["Kotlin", "Android", "앱개발", "Jetpack"],
    },
    {
        "title": "패션디자인·봉제 기능사 과정",
        "provider": "패션 직업훈련원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 중랑",
        "summary": "패션디자인, 의복 구성, 봉제 기술을 배우고 패션디자인기능사 자격을 취득합니다.",
        "target_audience": "의류 제조·디자인 직무 희망자",
        "skills": "패턴제작 봉제 의복구성 패션디자인 CAD패턴",
        "benefits": "패션디자인기능사 합격 보장",
        "schedule": "12주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-tex-002",
        "ncs_code": "18", "ncs_name": "섬유의복",
        "tags": ["패션디자인", "봉제", "패턴", "의복"],
    },
    {
        "title": "스포츠 시설 운영·생활스포츠지도사 과정",
        "provider": "스포츠 아카데미",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 송파",
        "summary": "생활스포츠지도사 2급 취득을 위한 스포츠 심리, 원리, 종목별 실기 과정입니다.",
        "target_audience": "스포츠 강사, 트레이너 직무 희망자",
        "skills": "스포츠심리 운동생리 코칭이론 종목실기",
        "benefits": "생활스포츠지도사 2급 취득 지원",
        "schedule": "12주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-sport-001",
        "ncs_code": "12", "ncs_name": "이용숙박여행오락스포츠",
        "tags": ["스포츠지도사", "트레이너", "생활스포츠"],
    },
    {
        "title": "제과제빵기능사 취득 과정",
        "provider": "베이킹 직업전문학교",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 은평",
        "summary": "제과기능사·제빵기능사 실기 집중 훈련 과정입니다. 케이크, 빵, 쿠키 50종을 실습합니다.",
        "target_audience": "제과제빵 직무 취업 및 창업 희망자",
        "skills": "제과 제빵 케이크데코 반죽발효 위생관리",
        "benefits": "기능사 합격 보장, 베이커리 취업 연계",
        "schedule": "8주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-food-004",
        "ncs_code": "13", "ncs_name": "음식서비스",
        "tags": ["제과제빵", "베이킹", "기능사", "창업"],
    },
    {
        "title": "전기차·수소차 정비 과정",
        "provider": "미래차 정비 아카데미",
        "program_type": "kdt",
        "category": "국민내일배움카드 훈련과정",
        "location": "경기 화성",
        "summary": "전기차 배터리 시스템, 수소연료전지, BMS, OBC 등 친환경차 정비 실무를 배웁니다.",
        "target_audience": "자동차 정비사, 친환경차 직무 전환 희망자",
        "skills": "전기차정비 BMS 배터리시스템 수소연료전지 OBD",
        "benefits": "자동차 기업 채용 연계",
        "schedule": "12주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-mec-009",
        "ncs_code": "15", "ncs_name": "기계",
        "tags": ["전기차", "수소차", "정비", "친환경차"],
    },
    {
        "title": "의약품 품질관리 QA/QC 과정",
        "provider": "제약 인재개발원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "충북 오송",
        "summary": "GMP 기준의 의약품 제조 품질관리 실무를 배웁니다. 완제의약품, 원료의약품 QC를 다룹니다.",
        "target_audience": "제약 QA/QC 직무 희망자",
        "skills": "GMP QA QC HPLC 의약품법규 품질시스템",
        "benefits": "제약사 QC 취업 연계",
        "schedule": "10주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-chem-002",
        "ncs_code": "17", "ncs_name": "화학",
        "tags": ["제약", "GMP", "QA", "QC"],
    },
    {
        "title": "아동·청소년 심리상담사 과정",
        "provider": "심리상담 아카데미",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 강북",
        "summary": "아동·청소년 발달심리, 상담이론, 집단상담 방법을 배우고 심리상담사 자격을 취득합니다.",
        "target_audience": "청소년 상담 직무 희망자",
        "skills": "발달심리 상담이론 집단상담 심리검사 미술치료",
        "benefits": "청소년상담사 자격 취득 지원",
        "schedule": "12주 · 주 4일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-soc-003",
        "ncs_code": "07", "ncs_name": "사회복지종교",
        "tags": ["심리상담", "청소년상담", "상담사", "복지"],
    },
    {
        "title": "빌딩 에너지 관리 시스템(BEMS) 운용 과정",
        "provider": "건물에너지 교육원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 송파",
        "summary": "BAS, BMS, BEMS를 활용한 빌딩 설비 에너지 모니터링 및 최적화 실무를 배웁니다.",
        "target_audience": "건물 에너지관리 직무 희망자",
        "skills": "BEMS BAS 설비관리 에너지절감 건물자동화",
        "benefits": "건물에너지관리사 취득 지원",
        "schedule": "8주 · 주 4일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-env-005",
        "ncs_code": "23", "ncs_name": "환경에너지안전",
        "tags": ["BEMS", "빌딩에너지", "설비관리", "에너지"],
    },
    {
        "title": "관광통역안내사 취득 과정",
        "provider": "관광 전문 교육원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "서울 중구",
        "summary": "관광통역안내사 1차(필기)·2차(면접) 대비 과정으로 관광법규, 국사, 관광자원을 다룹니다.",
        "target_audience": "관광통역안내사 자격 취득 희망자",
        "skills": "관광통역 외국어회화 관광자원 국사 관광법규",
        "benefits": "자격 취득 후 여행사 취업 연계",
        "schedule": "10주 · 주 4일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-tour-001",
        "ncs_code": "12", "ncs_name": "이용숙박여행오락스포츠",
        "tags": ["관광통역안내사", "관광", "통역", "자격증"],
    },
    {
        "title": "건설기계 운전 기능사 과정",
        "provider": "중장비 직업훈련원",
        "program_type": "training",
        "category": "국민내일배움카드 훈련과정",
        "location": "경기 포천",
        "summary": "굴삭기·지게차·로더 운전기능사 실기 집중 훈련 과정입니다.",
        "target_audience": "건설기계 운전 직종 취업 희망자",
        "skills": "굴삭기운전 지게차운전 로더운전 안전관리",
        "benefits": "운전기능사 합격 보장, 건설사 취업",
        "schedule": "6주 · 주 5일", "tuition": "국비지원", "url": "",
        "source": "sample", "external_id": "s-con-006",
        "ncs_code": "14", "ncs_name": "건설",
        "tags": ["굴삭기", "지게차", "건설기계", "기능사"],
    },
]
