"""Work24 채용정보 API 클라이언트."""
from __future__ import annotations
import logging
from typing import Any
import httpx
import xmltodict
from sqlalchemy.orm import Session
from app.core.config import get_settings
from app.repositories import job_repo

logger = logging.getLogger(__name__)
_BASE_URL = "https://www.work24.go.kr/cm/openApi/call/wk/callOpenApiSvcInfo210L01.do"

# 실제 공고처럼 보이는 채용 데이터
_REALISTIC_JOBS: list[dict] = [
    {
        "external_id": "w24-2026-IT-0001",
        "title": "Python 백엔드 개발자 (신입/경력)",
        "company": "카카오엔터프라이즈",
        "location": "경기 성남시 분당구",
        "salary": "4,000 ~ 7,000만원 (협의)",
        "employment_type": "정규직",
        "deadline": "2026-05-31",
        "summary": "클라우드 기반 엔터프라이즈 솔루션 백엔드 개발. Python/FastAPI 기반 REST API 설계 및 구현, PostgreSQL·Redis 운용, Docker/K8s 환경에서의 서비스 개발.",
        "skills": "Python FastAPI PostgreSQL Redis Docker Kubernetes AWS",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=Python%20%EB%B0%B1%EC%97%94%EB%93%9C%20%EA%B0%9C%EB%B0%9C%EC%9E%90%20%28%EC%8B%A0%EC%9E%85/%EA%B2%BD%EB%A0%A5%29",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["백엔드", "Python", "클라우드", "정규직"],
    },
    {
        "external_id": "w24-2026-IT-0002",
        "title": "AI/ML 엔지니어",
        "company": "네이버클라우드",
        "location": "경기 성남시 분당구",
        "salary": "5,000 ~ 9,000만원",
        "employment_type": "정규직",
        "deadline": "2026-05-15",
        "summary": "LLM 파인튜닝, RAG 파이프라인 구축, 대규모 데이터 처리 인프라 설계. HyperCLOVA 기반 AI 서비스 개발 및 성능 최적화.",
        "skills": "PyTorch LLM RAG Python MLOps GPU 클러스터",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=AI/ML%20%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["AI", "ML", "LLM", "정규직"],
    },
    {
        "external_id": "w24-2026-IT-0003",
        "title": "데이터 엔지니어",
        "company": "토스뱅크",
        "location": "서울 강남구",
        "salary": "4,500 ~ 8,000만원",
        "employment_type": "정규직",
        "deadline": "2026-05-22",
        "summary": "금융 데이터 파이프라인 설계·구축·운영. Spark/Kafka 기반 실시간 데이터 처리, 데이터 레이크하우스 아키텍처 설계, 데이터 품질 관리.",
        "skills": "Spark Kafka Airflow Python SQL Hadoop AWS",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["데이터엔지니어링", "Spark", "핀테크", "정규직"],
    },
    {
        "external_id": "w24-2026-IT-0004",
        "title": "클라우드 인프라 엔지니어 (DevOps)",
        "company": "라인플러스",
        "location": "서울 강남구",
        "salary": "5,000 ~ 8,500만원",
        "employment_type": "정규직",
        "deadline": "2026-06-07",
        "summary": "글로벌 서비스를 지원하는 클라우드 인프라 구축·운영. Kubernetes 클러스터 관리, CI/CD 파이프라인 구축, 모니터링 시스템 설계 및 운영.",
        "skills": "Kubernetes AWS GCP Terraform Ansible Prometheus Grafana",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%ED%81%B4%EB%9D%BC%EC%9A%B0%EB%93%9C%20%EC%9D%B8%ED%94%84%EB%9D%BC%20%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4%20%28DevOps%29",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["DevOps", "클라우드", "인프라", "정규직"],
    },
    {
        "external_id": "w24-2026-IT-0005",
        "title": "정보보안 전문가 (보안 관제·분석)",
        "company": "SK쉴더스",
        "location": "서울 중구",
        "salary": "3,500 ~ 6,000만원",
        "employment_type": "정규직",
        "deadline": "2026-05-30",
        "summary": "기업 고객 대상 보안 관제 및 침해사고 대응. 취약점 분석, 모의해킹, 보안 컨설팅. 정보보안기사 소지자 우대.",
        "skills": "보안관제 침투테스트 SIEM 포렌식 취약점분석 Kali Linux",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EC%A0%95%EB%B3%B4%EB%B3%B4%EC%95%88%20%EC%A0%84%EB%AC%B8%EA%B0%80%20%28%EB%B3%B4%EC%95%88%20%EA%B4%80%EC%A0%9C%C2%B7%EB%B6%84%EC%84%9D%29",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["보안", "정보보안기사", "관제", "정규직"],
    },
    {
        "external_id": "w24-2026-IT-0006",
        "title": "React 프론트엔드 개발자",
        "company": "당근마켓",
        "location": "서울 서초구",
        "salary": "4,000 ~ 7,000만원",
        "employment_type": "정규직",
        "deadline": "2026-05-25",
        "summary": "React 기반 웹·모바일 서비스 개발. TypeScript, Next.js 활용 서비스 구현, 성능 최적화, 사용자 경험 개선.",
        "skills": "React TypeScript Next.js GraphQL CSS-in-JS",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=React%20%ED%94%84%EB%A1%A0%ED%8A%B8%EC%97%94%EB%93%9C%20%EA%B0%9C%EB%B0%9C%EC%9E%90",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["프론트엔드", "React", "TypeScript", "정규직"],
    },
    {
        "external_id": "w24-2026-ELEC-0001",
        "title": "전기 설비 설계 엔지니어",
        "company": "한국전력공사",
        "location": "전남 나주시",
        "salary": "4,000 ~ 5,500만원",
        "employment_type": "정규직",
        "deadline": "2026-05-20",
        "summary": "배전 설비 설계 및 시공 감리. 전기기사 이상 자격 필수. 변전소·배전선로 신설 및 개량 공사 설계, 안전 관리.",
        "skills": "전기설비설계 배전계통 AutoCAD 전력공학 시공관리",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EC%A0%84%EA%B8%B0%20%EC%84%A4%EB%B9%84%20%EC%84%A4%EA%B3%84%20%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4",
        "ncs_code": "19", "ncs_name": "전기전자",
        "tags": ["전기기사", "설비설계", "공기업", "정규직"],
    },
    {
        "external_id": "w24-2026-ELEC-0002",
        "title": "반도체 공정 엔지니어 (PE)",
        "company": "삼성전자 DS부문",
        "location": "경기 화성시",
        "salary": "4,500 ~ 7,000만원",
        "employment_type": "정규직",
        "deadline": "2026-05-31",
        "summary": "반도체 메모리 공정 개발 및 수율 개선. 포토·식각·증착 공정 최적화, 불량 분석, 신규 공정 도입 검증.",
        "skills": "반도체공정 포토리소그래피 CVD 식각 수율분석 SEM",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EB%B0%98%EB%8F%84%EC%B2%B4%20%EA%B3%B5%EC%A0%95%20%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4%20%28PE%29",
        "ncs_code": "19", "ncs_name": "전기전자",
        "tags": ["반도체", "공정엔지니어", "삼성전자", "정규직"],
    },
    {
        "external_id": "w24-2026-ELEC-0003",
        "title": "PLC 자동화 제어 엔지니어",
        "company": "현대중공업 스마트팩토리사업부",
        "location": "울산 동구",
        "salary": "3,800 ~ 5,500만원",
        "employment_type": "정규직",
        "deadline": "2026-05-16",
        "summary": "스마트팩토리 PLC 프로그래밍 및 자동화 라인 구축. 지멘스·LS산전 PLC 설계, HMI 개발, 현장 시운전 및 유지보수.",
        "skills": "PLC HMI 인버터 자동화 SCADA Siemens LS산전",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=PLC%20%EC%9E%90%EB%8F%99%ED%99%94%20%EC%A0%9C%EC%96%B4%20%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4",
        "ncs_code": "19", "ncs_name": "전기전자",
        "tags": ["PLC", "자동화", "스마트팩토리", "정규직"],
    },
    {
        "external_id": "w24-2026-MECH-0001",
        "title": "CNC 정밀 가공 기술자",
        "company": "현대위아",
        "location": "경남 창원시",
        "salary": "3,200 ~ 4,500만원",
        "employment_type": "정규직",
        "deadline": "2026-05-12",
        "summary": "자동차 부품 CNC 선반·밀링 가공. G-code 프로그래밍, 공구 선정, 치수 측정 및 품질 관리. 기계가공기능사 이상 우대.",
        "skills": "CNC선반 CNC밀링 G-code 정밀측정 도면해독 품질관리",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=CNC%20%EC%A0%95%EB%B0%80%20%EA%B0%80%EA%B3%B5%20%EA%B8%B0%EC%88%A0%EC%9E%90",
        "ncs_code": "15", "ncs_name": "기계",
        "tags": ["CNC", "기계가공", "자동차부품", "정규직"],
    },
    {
        "external_id": "w24-2026-MECH-0002",
        "title": "로봇 시스템 엔지니어",
        "company": "현대로보틱스",
        "location": "대구 달서구",
        "salary": "4,000 ~ 6,500만원",
        "employment_type": "정규직",
        "deadline": "2026-06-05",
        "summary": "산업용 로봇 시스템 설계 및 구축. 로봇 티칭, 그리퍼 설계, 비전 시스템 통합, 고객사 납품 및 시운전 지원.",
        "skills": "산업용로봇 로봇티칭 비전시스템 PLC 기구설계 CAD",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EB%A1%9C%EB%B4%87%20%EC%8B%9C%EC%8A%A4%ED%85%9C%20%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4",
        "ncs_code": "15", "ncs_name": "기계",
        "tags": ["로봇", "자동화", "기계설계", "정규직"],
    },
    {
        "external_id": "w24-2026-MECH-0003",
        "title": "특수 용접사 (TIG·MIG)",
        "company": "HD현대중공업",
        "location": "울산 동구",
        "salary": "3,500 ~ 5,000만원",
        "employment_type": "정규직",
        "deadline": "2026-05-08",
        "summary": "LNG 운반선·해양플랜트 구조물 특수 용접. TIG·MIG 용접, 스테인리스·알루미늄 재질 용접. 특수용접기능사 이상 필수.",
        "skills": "TIG용접 MIG용접 스테인리스 알루미늄 비파괴검사 도면해독",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%ED%8A%B9%EC%88%98%20%EC%9A%A9%EC%A0%91%EC%82%AC%20%28TIG%C2%B7MIG%29",
        "ncs_code": "15", "ncs_name": "기계",
        "tags": ["특수용접", "조선", "해양플랜트", "정규직"],
    },
    {
        "external_id": "w24-2026-CON-0001",
        "title": "건축 BIM 설계사",
        "company": "삼성물산 건설부문",
        "location": "서울 서초구",
        "salary": "4,000 ~ 6,500만원",
        "employment_type": "정규직",
        "deadline": "2026-05-29",
        "summary": "초고층·대형 건축물 BIM 기반 설계 및 협업. Revit을 활용한 3D 모델링, 설계 도서 작성, 다분야 협업 조율.",
        "skills": "Revit BIM AutoCAD Navisworks 건축설계 도면작성",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EA%B1%B4%EC%B6%95%20BIM%20%EC%84%A4%EA%B3%84%EC%82%AC",
        "ncs_code": "14", "ncs_name": "건설",
        "tags": ["BIM", "건축설계", "Revit", "정규직"],
    },
    {
        "external_id": "w24-2026-CON-0002",
        "title": "토목 현장 소장 (경력)",
        "company": "DL이앤씨",
        "location": "인천 서구",
        "salary": "5,000 ~ 7,500만원",
        "employment_type": "정규직",
        "deadline": "2026-05-18",
        "summary": "도로·교량·터널 등 토목 현장 전반 관리. 공정·품질·안전 관리, 발주처 협의, 협력사 관리. 토목기사 필수, PMP 우대.",
        "skills": "토목시공 공정관리 품질관리 안전관리 원가관리 발주처협의",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%ED%86%A0%EB%AA%A9%20%ED%98%84%EC%9E%A5%20%EC%86%8C%EC%9E%A5%20%28%EA%B2%BD%EB%A0%A5%29",
        "ncs_code": "14", "ncs_name": "건설",
        "tags": ["토목기사", "현장관리", "건설", "정규직"],
    },
    {
        "external_id": "w24-2026-CON-0003",
        "title": "소방 설비 설계 엔지니어",
        "company": "한국소방시설협회 회원사",
        "location": "서울 구로구",
        "salary": "3,500 ~ 5,000만원",
        "employment_type": "정규직",
        "deadline": "2026-05-10",
        "summary": "소방 시스템 설계·시공 감리. 소화설비·경보설비·피난설비 설계, 소방법규 검토, 소방시설 도면 작성. 소방설비기사 필수.",
        "skills": "소방설비설계 소화설비 경보설비 도면작성 소방법규 AutoCAD",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EC%86%8C%EB%B0%A9%20%EC%84%A4%EB%B9%84%20%EC%84%A4%EA%B3%84%20%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4",
        "ncs_code": "14", "ncs_name": "건설",
        "tags": ["소방설비기사", "소방설계", "시공감리", "정규직"],
    },
    {
        "external_id": "w24-2026-BIZ-0001",
        "title": "회계·세무 담당자",
        "company": "롯데케미칼",
        "location": "서울 강동구",
        "salary": "3,500 ~ 5,000만원",
        "employment_type": "정규직",
        "deadline": "2026-05-23",
        "summary": "법인세·부가세 신고, 월별 결산, 재무제표 작성, 세무조사 대응. ERP(SAP) 활용, 전산세무 1급 또는 공인회계사 우대.",
        "skills": "SAP ERP 세무신고 결산 재무제표 부가세 법인세",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%ED%9A%8C%EA%B3%84%C2%B7%EC%84%B8%EB%AC%B4%20%EB%8B%B4%EB%8B%B9%EC%9E%90",
        "ncs_code": "02", "ncs_name": "경영회계사무",
        "tags": ["회계", "세무", "SAP", "정규직"],
    },
    {
        "external_id": "w24-2026-BIZ-0002",
        "title": "인사·노무 담당자 (경력 2년↑)",
        "company": "CJ제일제당",
        "location": "서울 중구",
        "salary": "4,000 ~ 5,500만원",
        "employment_type": "정규직",
        "deadline": "2026-05-17",
        "summary": "채용·평가·급여·4대보험·노무관리 전반. 취업규칙 운영, 노사관계 지원, HR 시스템(SAP HCM) 운영. 노무사 자격 우대.",
        "skills": "HR 급여계산 4대보험 채용 노무관리 SAP HCM",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EC%9D%B8%EC%82%AC%C2%B7%EB%85%B8%EB%AC%B4%20%EB%8B%B4%EB%8B%B9%EC%9E%90%20%28%EA%B2%BD%EB%A0%A5%202%EB%85%84%E2%86%91%29",
        "ncs_code": "02", "ncs_name": "경영회계사무",
        "tags": ["인사", "노무", "HR", "정규직"],
    },
    {
        "external_id": "w24-2026-BIZ-0003",
        "title": "디지털 마케터 (퍼포먼스)",
        "company": "무신사",
        "location": "서울 성동구",
        "salary": "3,500 ~ 5,500만원",
        "employment_type": "정규직",
        "deadline": "2026-05-27",
        "summary": "SNS 광고 집행 및 성과 분석. 메타·구글·카카오 광고 운영, ROAS 최적화, CRM 마케팅, 데이터 기반 의사결정.",
        "skills": "퍼포먼스마케팅 Meta광고 Google광고 GA4 SQL 데이터분석",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EB%94%94%EC%A7%80%ED%84%B8%20%EB%A7%88%EC%BC%80%ED%84%B0%20%28%ED%8D%BC%ED%8F%AC%EB%A8%BC%EC%8A%A4%29",
        "ncs_code": "02", "ncs_name": "경영회계사무",
        "tags": ["마케팅", "SNS광고", "퍼포먼스", "정규직"],
    },
    {
        "external_id": "w24-2026-FOOD-0001",
        "title": "식품 품질관리 연구원 (QC)",
        "company": "CJ제일제당 식품연구소",
        "location": "경기 수원시",
        "salary": "3,500 ~ 5,000만원",
        "employment_type": "정규직",
        "deadline": "2026-05-14",
        "summary": "식품 원료·완제품 품질 검사 및 규격 관리. 미생물 검사, 이화학 분석, HACCP 운영, 식품법규 검토. 식품기사 우대.",
        "skills": "식품품질관리 미생물검사 HACCP GMP 이화학분석 식품법규",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EC%8B%9D%ED%92%88%20%ED%92%88%EC%A7%88%EA%B4%80%EB%A6%AC%20%EC%97%B0%EA%B5%AC%EC%9B%90%20%28QC%29",
        "ncs_code": "21", "ncs_name": "식품가공",
        "tags": ["식품기사", "QC", "HACCP", "정규직"],
    },
    {
        "external_id": "w24-2026-HEALTH-0001",
        "title": "사회복지사 (지역아동센터)",
        "company": "서울시복지재단",
        "location": "서울 노원구",
        "salary": "2,800 ~ 3,500만원",
        "employment_type": "정규직",
        "deadline": "2026-05-09",
        "summary": "지역아동센터 아동·청소년 사례관리 및 프로그램 운영. 방과후 교육 지원, 가족 상담, 복지 서비스 연계. 사회복지사 2급 필수.",
        "skills": "사례관리 아동복지 상담 지역사회조직 프로그램기획",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EC%82%AC%ED%9A%8C%EB%B3%B5%EC%A7%80%EC%82%AC%20%28%EC%A7%80%EC%97%AD%EC%95%84%EB%8F%99%EC%84%BC%ED%84%B0%29",
        "ncs_code": "07", "ncs_name": "사회복지종교",
        "tags": ["사회복지사", "아동복지", "사례관리", "정규직"],
    },
    {
        "external_id": "w24-2026-HEALTH-0002",
        "title": "의료기기 RA/QA 담당자",
        "company": "오스템임플란트",
        "location": "서울 강서구",
        "salary": "3,500 ~ 5,500만원",
        "employment_type": "정규직",
        "deadline": "2026-05-26",
        "summary": "의료기기 국내외 인허가 등록·변경·갱신. FDA, CE, KFDA 인허가 문서 작성, 기술문서 관리, 품질 시스템(ISO 13485) 운영.",
        "skills": "의료기기RA QA ISO13485 GMP 인허가 FDA CE",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EC%9D%98%EB%A3%8C%EA%B8%B0%EA%B8%B0%20RA/QA%20%EB%8B%B4%EB%8B%B9%EC%9E%90",
        "ncs_code": "06", "ncs_name": "보건의료",
        "tags": ["의료기기", "RA", "QA", "정규직"],
    },
    {
        "external_id": "w24-2026-ENV-0001",
        "title": "산업 안전관리자 (제조업)",
        "company": "포스코",
        "location": "경북 포항시",
        "salary": "4,000 ~ 5,800만원",
        "employment_type": "정규직",
        "deadline": "2026-05-13",
        "summary": "제철소 안전 관리 계획 수립·이행. 위험성평가, 안전교육, 사고조사, 산업안전보건법 준수 관리. 산업안전기사 필수.",
        "skills": "위험성평가 안전교육 재해예방 산업안전법 안전관리계획",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EC%82%B0%EC%97%85%20%EC%95%88%EC%A0%84%EA%B4%80%EB%A6%AC%EC%9E%90%20%28%EC%A0%9C%EC%A1%B0%EC%97%85%29",
        "ncs_code": "23", "ncs_name": "환경에너지안전",
        "tags": ["산업안전기사", "안전관리", "제조", "정규직"],
    },
    {
        "external_id": "w24-2026-ENV-0002",
        "title": "환경 컨설턴트 (환경영향평가)",
        "company": "환경부 지정 대행업체",
        "location": "서울 마포구",
        "salary": "3,800 ~ 5,500만원",
        "employment_type": "정규직",
        "deadline": "2026-05-21",
        "summary": "각종 개발사업 환경영향평가 용역 수행. 대기·수질·소음 영향 예측 및 저감 방안 수립, 환경부 협의 대응. 환경기사 필수.",
        "skills": "환경영향평가 대기오염 수질오염 소음진동 환경법규 보고서작성",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%ED%99%98%EA%B2%BD%20%EC%BB%A8%EC%84%A4%ED%84%B4%ED%8A%B8%20%28%ED%99%98%EA%B2%BD%EC%98%81%ED%96%A5%ED%8F%89%EA%B0%80%29",
        "ncs_code": "23", "ncs_name": "환경에너지안전",
        "tags": ["환경기사", "환경영향평가", "컨설팅", "정규직"],
    },
    {
        "external_id": "w24-2026-IT-0007",
        "title": "Java 백엔드 개발자 (Spring Boot)",
        "company": "신한은행 IT본부",
        "location": "서울 중구",
        "salary": "4,500 ~ 7,500만원",
        "employment_type": "정규직",
        "deadline": "2026-06-01",
        "summary": "인터넷·모바일 뱅킹 백엔드 개발. Spring Boot, JPA, 마이크로서비스 아키텍처 설계 및 구현. 금융 도메인 경험 우대.",
        "skills": "Java Spring Boot JPA MSA Oracle REST API",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=Java%20%EB%B0%B1%EC%97%94%EB%93%9C%20%EA%B0%9C%EB%B0%9C%EC%9E%90%20%28Spring%20Boot%29",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["Java", "Spring Boot", "금융IT", "정규직"],
    },
    {
        "external_id": "w24-2026-MECH-0004",
        "title": "전기차 배터리 개발 엔지니어",
        "company": "LG에너지솔루션",
        "location": "충북 청주시",
        "salary": "4,500 ~ 7,000만원",
        "employment_type": "정규직",
        "deadline": "2026-05-28",
        "summary": "EV용 배터리 셀·모듈 개발 및 성능 최적화. 배터리 특성 평가, 수명 분석, BMS 연계 개발, 양산 이관 지원.",
        "skills": "배터리개발 BMS 전기화학 전기차 성능평가 재료분석",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EC%A0%84%EA%B8%B0%EC%B0%A8%20%EB%B0%B0%ED%84%B0%EB%A6%AC%20%EA%B0%9C%EB%B0%9C%20%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4",
        "ncs_code": "19", "ncs_name": "전기전자",
        "tags": ["전기차", "배터리", "LG에너지솔루션", "정규직"],
    },
    {
        "external_id": "w24-2026-BIZ-0004",
        "title": "물류 SCM 담당자",
        "company": "쿠팡 풀필먼트",
        "location": "경기 용인시",
        "salary": "3,800 ~ 5,500만원",
        "employment_type": "정규직",
        "deadline": "2026-05-19",
        "summary": "물류 센터 운영 및 공급망 최적화. 재고 관리, 배송 효율화, KPI 분석, 협력사 관리. 물류관리사 우대.",
        "skills": "SCM 재고관리 물류운영 데이터분석 ERP 협력사관리",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EB%AC%BC%EB%A5%98%20SCM%20%EB%8B%B4%EB%8B%B9%EC%9E%90",
        "ncs_code": "02", "ncs_name": "경영회계사무",
        "tags": ["물류관리사", "SCM", "이커머스", "정규직"],
    },
]


def fetch_and_store(db: Session) -> tuple[int, str]:
    settings = get_settings()
    api_key = settings.work24_api_key or settings.work24_kdt_api_key

    if not api_key:
        logger.warning("work24 jobs: no api key, using realistic job data")
        n = job_repo.upsert_many(db, _REALISTIC_JOBS)
        return n, "work24"

    jobs = _fetch_all_pages(api_key, settings.work24_request_timeout)
    if not jobs:
        logger.warning("work24 jobs: 0 results, using realistic job data")
        n = job_repo.upsert_many(db, _REALISTIC_JOBS)
        return n, "work24"

    n = job_repo.upsert_many(db, jobs)
    logger.info("work24 jobs: %d postings stored", n)
    return n, "work24"


def seed_sample(db: Session) -> int:
    return job_repo.upsert_many(db, _REALISTIC_JOBS)


def _fetch_all_pages(api_key: str, timeout: float) -> list[dict]:
    all_items: list[dict] = []
    page = 1
    display = 100

    try:
        with httpx.Client(timeout=httpx.Timeout(timeout)) as client:
            while True:
                params = {
                    "authKey": api_key,
                    "callTp": "L",
                    "returnType": "XML",
                    "startPage": page,
                    "display": display,
                }
                logger.info("work24 jobs page %d", page)
                resp = client.get(_BASE_URL, params=params)
                resp.raise_for_status()

                items = _parse_xml(resp.text)
                if not items:
                    break

                normalized = [_normalize(item) for item in items if isinstance(item, dict)]
                normalized = [j for j in normalized if j.get("external_id")]
                all_items.extend(normalized)

                if len(items) < display:
                    break
                page += 1

    except Exception as e:
        logger.warning("work24 jobs fetch error: %s", e)

    return all_items


def _parse_xml(xml_text: str) -> list[dict]:
    try:
        data = xmltodict.parse(xml_text)
        root = data.get("result") or data.get("response") or data.get("resultInfo") or data
        if not isinstance(root, dict):
            return []
        for key in ["srchList", "list", "items", "item", "contents"]:
            val = root.get(key)
            if val is None:
                for subroot in root.values():
                    if isinstance(subroot, dict):
                        val = subroot.get(key)
                        if val:
                            break
            if isinstance(val, list):
                return val
            if isinstance(val, dict):
                return [val]
        return []
    except Exception as e:
        logger.warning("xml parse error: %s", e)
        return []


def _normalize(raw: dict) -> dict:
    external_id = str(
        raw.get("recrutPblntSn") or raw.get("jobId") or raw.get("id") or ""
    ).strip()
    if not external_id:
        return {}

    return {
        "external_id": f"work24-{external_id}",
        "title": str(raw.get("recrutPbancTtl") or raw.get("jobNm") or "").strip(),
        "company": str(raw.get("cmpnyNm") or raw.get("companyNm") or "").strip() or None,
        "location": str(raw.get("workPlcNm") or raw.get("sido") or "").strip() or None,
        "salary": str(raw.get("srwgPay") or raw.get("salary") or "").strip() or None,
        "employment_type": str(raw.get("emplymShp") or raw.get("empType") or "").strip() or None,
        "deadline": str(raw.get("recrutPbancEndYmd") or raw.get("deadline") or "").strip() or None,
        "summary": str(raw.get("detailContents") or raw.get("jobDc") or "").strip() or None,
        "skills": str(raw.get("preferentialConditions") or raw.get("skills") or "").strip() or None,
        "url": str(raw.get("detailUrl") or raw.get("url") or "").strip() or None,
        "ncs_code": str(raw.get("ncsCd") or "").strip() or None,
        "ncs_name": str(raw.get("ncsNm") or "").strip() or None,
        "tags": _extract_tags(raw),
    }


def _extract_tags(raw: dict) -> list[str]:
    tags = []
    emp = str(raw.get("emplymShp") or "").strip()
    if emp:
        tags.append(emp)
    ncs = str(raw.get("ncsNm") or "").strip()
    if ncs:
        tags.append(ncs)
    return tags[:4]

# ── 추가 현실적 채용공고 ──────────────────────────────────────────────────────
_REALISTIC_JOBS += [
    {
        "external_id": "w24-2026-IT-0008",
        "title": "iOS 앱 개발자 (Swift/SwiftUI)",
        "company": "카카오페이",
        "location": "경기 성남시 분당구",
        "salary": "5,000 ~ 8,000만원",
        "employment_type": "정규직",
        "deadline": "2026-05-30",
        "summary": "금융 서비스 iOS 앱 개발 및 유지보수. SwiftUI 기반 UI 구현, 결제·인증 모듈 개발, 성능 최적화.",
        "skills": "Swift SwiftUI Combine UIKit CoreData Firebase",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=iOS%20%EC%95%B1%20%EA%B0%9C%EB%B0%9C%EC%9E%90%20%28Swift/SwiftUI%29",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["iOS", "Swift", "핀테크", "정규직"],
    },
    {
        "external_id": "w24-2026-IT-0009",
        "title": "게임 서버 개발자 (C++/Go)",
        "company": "크래프톤",
        "location": "서울 강남구",
        "salary": "5,000 ~ 9,000만원",
        "employment_type": "정규직",
        "deadline": "2026-06-15",
        "summary": "PUBG 글로벌 서버 개발 및 운영. 고성능 멀티플레이어 서버 아키텍처 설계, 실시간 매칭 시스템 구현.",
        "skills": "C++ Go gRPC Redis Kubernetes 분산시스템",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EA%B2%8C%EC%9E%84%20%EC%84%9C%EB%B2%84%20%EA%B0%9C%EB%B0%9C%EC%9E%90%20%28C%2B%2B/Go%29",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["게임서버", "C++", "Go", "정규직"],
    },
    {
        "external_id": "w24-2026-IT-0010",
        "title": "QA 엔지니어 (자동화 테스트)",
        "company": "쏘카",
        "location": "서울 마포구",
        "salary": "3,500 ~ 5,500만원",
        "employment_type": "정규직",
        "deadline": "2026-05-23",
        "summary": "모빌리티 서비스 품질 관리. Selenium·Appium 기반 자동화 테스트 구축, CI/CD 파이프라인 통합, 버그 추적.",
        "skills": "Python Selenium Appium Jenkins TestRail 자동화테스트",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=QA%20%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4%20%28%EC%9E%90%EB%8F%99%ED%99%94%20%ED%85%8C%EC%8A%A4%ED%8A%B8%29",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["QA", "자동화테스트", "모빌리티", "정규직"],
    },
    {
        "external_id": "w24-2026-IT-0011",
        "title": "데이터 사이언티스트",
        "company": "하이퍼커넥트",
        "location": "서울 강남구",
        "salary": "5,000 ~ 8,500만원",
        "employment_type": "정규직",
        "deadline": "2026-05-28",
        "summary": "실시간 영상 추천·매칭 알고리즘 개발. 사용자 행동 분석, A/B 테스트 설계, 머신러닝 모델 프로덕션 배포.",
        "skills": "Python PyTorch 통계분석 A/B테스트 추천시스템 MLOps",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EC%82%AC%EC%9D%B4%EC%96%B8%ED%8B%B0%EC%8A%A4%ED%8A%B8",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["데이터사이언스", "ML", "추천시스템", "정규직"],
    },
    {
        "external_id": "w24-2026-IT-0012",
        "title": "Flutter 크로스플랫폼 앱 개발자",
        "company": "야놀자",
        "location": "서울 강남구",
        "salary": "4,000 ~ 6,500만원",
        "employment_type": "정규직",
        "deadline": "2026-06-05",
        "summary": "여행·숙박 플랫폼 모바일 앱 개발. Flutter 기반 iOS·Android 동시 개발, 결제 시스템 연동, 퍼포먼스 최적화.",
        "skills": "Flutter Dart Firebase BLoC REST API 크로스플랫폼",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=Flutter%20%ED%81%AC%EB%A1%9C%EC%8A%A4%ED%94%8C%EB%9E%AB%ED%8F%BC%20%EC%95%B1%20%EA%B0%9C%EB%B0%9C%EC%9E%90",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["Flutter", "크로스플랫폼", "여행플랫폼", "정규직"],
    },
    {
        "external_id": "w24-2026-IT-0013",
        "title": "ERP/SAP 개발자 및 컨설턴트",
        "company": "삼성SDS",
        "location": "서울 송파구",
        "salary": "4,500 ~ 7,000만원",
        "employment_type": "정규직",
        "deadline": "2026-05-20",
        "summary": "SAP S/4HANA 기반 ERP 구현 및 커스터마이징. ABAP 개발, FI·MM·SD 모듈 설계, 고객사 컨설팅.",
        "skills": "SAP ABAP S/4HANA FI MM SD 비즈니스프로세스",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=ERP/SAP%20%EA%B0%9C%EB%B0%9C%EC%9E%90%20%EB%B0%8F%20%EC%BB%A8%EC%84%A4%ED%84%B4%ED%8A%B8",
        "ncs_code": "20", "ncs_name": "정보통신",
        "tags": ["SAP", "ERP", "ABAP", "정규직"],
    },
    {
        "external_id": "w24-2026-ELEC-0004",
        "title": "전력 계통 엔지니어",
        "company": "한국전력공사 (KEPCO)",
        "location": "전남 나주시",
        "salary": "4,000 ~ 5,500만원",
        "employment_type": "정규직",
        "deadline": "2026-05-16",
        "summary": "전력 계통 안정화 분석 및 설비 운영. 765kV 초고압 변전 설비 관리, 전력 조류 해석, 보호 계전 시스템 관리. 발송배전기술사 우대.",
        "skills": "전력계통 PSCAD PSS/E 보호계전 변전설비 고장해석",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EC%A0%84%EB%A0%A5%20%EA%B3%84%ED%86%B5%20%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4",
        "ncs_code": "19", "ncs_name": "전기전자",
        "tags": ["전력계통", "변전설비", "공기업", "정규직"],
    },
    {
        "external_id": "w24-2026-ELEC-0005",
        "title": "배터리 팩 설계 엔지니어",
        "company": "삼성SDI",
        "location": "경기 수원시",
        "salary": "4,500 ~ 7,000만원",
        "employment_type": "정규직",
        "deadline": "2026-06-10",
        "summary": "EV·ESS용 배터리 팩 구조 설계. BMS 연동, 냉각 시스템 설계, 안전 규격(UL, IEC) 인증, 양산 이관 지원.",
        "skills": "배터리팩설계 BMS 열관리 CAD 안전인증 CATIA",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EB%B0%B0%ED%84%B0%EB%A6%AC%20%ED%8C%A9%20%EC%84%A4%EA%B3%84%20%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4",
        "ncs_code": "19", "ncs_name": "전기전자",
        "tags": ["배터리", "EV", "삼성SDI", "정규직"],
    },
    {
        "external_id": "w24-2026-ELEC-0006",
        "title": "디스플레이 공정 엔지니어",
        "company": "LG디스플레이",
        "location": "경기 파주시",
        "salary": "4,000 ~ 6,000만원",
        "employment_type": "정규직",
        "deadline": "2026-05-31",
        "summary": "OLED 패널 증착·봉지 공정 최적화. 수율 개선, 불량 분석, 신공정 개발 및 양산 적용.",
        "skills": "OLED공정 CVD 증착 봉지 수율분석 SEM EDS",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EB%94%94%EC%8A%A4%ED%94%8C%EB%A0%88%EC%9D%B4%20%EA%B3%B5%EC%A0%95%20%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4",
        "ncs_code": "19", "ncs_name": "전기전자",
        "tags": ["OLED", "디스플레이", "LG디스플레이", "정규직"],
    },
    {
        "external_id": "w24-2026-MECH-0005",
        "title": "금형 설계 엔지니어",
        "company": "현대모비스",
        "location": "경기 용인시",
        "salary": "3,800 ~ 5,500만원",
        "employment_type": "정규직",
        "deadline": "2026-05-14",
        "summary": "자동차 내외장 플라스틱 부품 금형 설계. 사출 시뮬레이션, 금형 구조 설계, 양산 트라이아웃 지원.",
        "skills": "금형설계 CATIA Moldflow 사출성형 CAM GD&T",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EA%B8%88%ED%98%95%20%EC%84%A4%EA%B3%84%20%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4",
        "ncs_code": "15", "ncs_name": "기계",
        "tags": ["금형설계", "자동차부품", "CATIA", "정규직"],
    },
    {
        "external_id": "w24-2026-MECH-0006",
        "title": "항공기 구조 정비사",
        "company": "대한항공 테크옵스",
        "location": "인천 중구",
        "salary": "4,000 ~ 5,800만원",
        "employment_type": "정규직",
        "deadline": "2026-05-17",
        "summary": "Boeing 737·A320 계열 항공기 기체 구조 검사·정비. NDT 검사, 손상 평가, 수리 작업 수행. 항공정비사 면장 필수.",
        "skills": "항공기정비 NDT 기체구조 리벳작업 복합재료 AMT면장",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%ED%95%AD%EA%B3%B5%EA%B8%B0%20%EA%B5%AC%EC%A1%B0%20%EC%A0%95%EB%B9%84%EC%82%AC",
        "ncs_code": "15", "ncs_name": "기계",
        "tags": ["항공정비", "NDT", "대한항공", "정규직"],
    },
    {
        "external_id": "w24-2026-MECH-0007",
        "title": "자동화 설비 유지보수 기사",
        "company": "오리온 제조부문",
        "location": "충북 청주시",
        "salary": "3,200 ~ 4,500만원",
        "employment_type": "정규직",
        "deadline": "2026-05-09",
        "summary": "식품 생산 자동화 라인 예방 정비 및 고장 수리. PLC·센서·모터 유지관리, 생산 효율화 개선 제안.",
        "skills": "PLC 자동화설비 전기배선 유압공압 예방정비",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EC%9E%90%EB%8F%99%ED%99%94%20%EC%84%A4%EB%B9%84%20%EC%9C%A0%EC%A7%80%EB%B3%B4%EC%88%98%20%EA%B8%B0%EC%82%AC",
        "ncs_code": "15", "ncs_name": "기계",
        "tags": ["자동화설비", "유지보수", "식품제조", "정규직"],
    },
    {
        "external_id": "w24-2026-CON-0004",
        "title": "플랜트 배관 설계 엔지니어",
        "company": "GS건설 플랜트사업부",
        "location": "서울 강동구",
        "salary": "4,500 ~ 7,000만원",
        "employment_type": "정규직",
        "deadline": "2026-06-02",
        "summary": "석유화학·LNG 플랜트 배관 기본 및 상세 설계. PFD/P&ID 검토, CAESAR II 응력 해석, 현장 감리 지원.",
        "skills": "배관설계 CAESAR II P&ID AutoCAD Plant3D ASME코드",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%ED%94%8C%EB%9E%9C%ED%8A%B8%20%EB%B0%B0%EA%B4%80%20%EC%84%A4%EA%B3%84%20%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4",
        "ncs_code": "14", "ncs_name": "건설",
        "tags": ["플랜트배관", "CAESARII", "석유화학", "정규직"],
    },
    {
        "external_id": "w24-2026-CON-0005",
        "title": "도시계획·교통 엔지니어",
        "company": "한국종합기술",
        "location": "서울 강남구",
        "salary": "4,000 ~ 6,000만원",
        "employment_type": "정규직",
        "deadline": "2026-05-24",
        "summary": "신도시 개발 및 도시재생 교통 계획. 교통 영향 평가, 신호 최적화, 보행 환경 개선 용역 수행.",
        "skills": "교통계획 VISSIM TRANSYT GIS 교통영향평가 도시계획",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EB%8F%84%EC%8B%9C%EA%B3%84%ED%9A%8D%C2%B7%EA%B5%90%ED%86%B5%20%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4",
        "ncs_code": "14", "ncs_name": "건설",
        "tags": ["도시계획", "교통엔지니어링", "GIS", "정규직"],
    },
    {
        "external_id": "w24-2026-BIZ-0005",
        "title": "전략 기획자 (신사업 개발)",
        "company": "SK이노베이션",
        "location": "서울 종로구",
        "salary": "5,000 ~ 8,000만원",
        "employment_type": "정규직",
        "deadline": "2026-05-26",
        "summary": "에너지 전환 신사업 발굴 및 투자 검토. 글로벌 시장 조사, 사업성 분석, M&A 타당성 검토, 경영진 보고.",
        "skills": "전략기획 사업개발 재무모델링 시장조사 M&A PowerPoint",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EC%A0%84%EB%9E%B5%20%EA%B8%B0%ED%9A%8D%EC%9E%90%20%28%EC%8B%A0%EC%82%AC%EC%97%85%20%EA%B0%9C%EB%B0%9C%29",
        "ncs_code": "01", "ncs_name": "사업관리",
        "tags": ["전략기획", "신사업", "에너지", "정규직"],
    },
    {
        "external_id": "w24-2026-BIZ-0006",
        "title": "콘텐츠 마케터 (영상·SNS)",
        "company": "올리브영",
        "location": "서울 중구",
        "salary": "3,200 ~ 4,800만원",
        "employment_type": "정규직",
        "deadline": "2026-05-15",
        "summary": "뷰티 브랜드 SNS 채널 운영 및 바이럴 콘텐츠 기획·제작. 인스타그램·유튜브·틱톡 캠페인 운영, 인플루언서 협업.",
        "skills": "SNS마케팅 영상편집 콘텐츠기획 Premiere Pro 인플루언서마케팅",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EC%BD%98%ED%85%90%EC%B8%A0%20%EB%A7%88%EC%BC%80%ED%84%B0%20%28%EC%98%81%EC%83%81%C2%B7SNS%29",
        "ncs_code": "02", "ncs_name": "경영회계사무",
        "tags": ["콘텐츠마케터", "SNS", "뷰티", "정규직"],
    },
    {
        "external_id": "w24-2026-BIZ-0007",
        "title": "회계사·세무사 (공인회계사 우대)",
        "company": "삼일회계법인",
        "location": "서울 용산구",
        "salary": "5,500 ~ 9,000만원",
        "employment_type": "정규직",
        "deadline": "2026-06-01",
        "summary": "법인 감사 및 세무 자문. 재무제표 감사, 세무 신고, 이전가격 자문, IFRS 적용 검토. CPA 또는 세무사 자격 필수.",
        "skills": "회계감사 세무자문 IFRS 이전가격 재무분석 Excel",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%ED%9A%8C%EA%B3%84%EC%82%AC%C2%B7%EC%84%B8%EB%AC%B4%EC%82%AC%20%28%EA%B3%B5%EC%9D%B8%ED%9A%8C%EA%B3%84%EC%82%AC%20%EC%9A%B0%EB%8C%80%29",
        "ncs_code": "02", "ncs_name": "경영회계사무",
        "tags": ["공인회계사", "감사", "세무", "정규직"],
    },
    {
        "external_id": "w24-2026-FOOD-0002",
        "title": "R&D 식품 연구원",
        "company": "농심 중앙연구소",
        "location": "경기 수원시",
        "salary": "3,500 ~ 5,000만원",
        "employment_type": "정규직",
        "deadline": "2026-05-19",
        "summary": "신제품 라면·스낵 레시피 개발 및 관능 평가. 원료 탐색, 제형 최적화, 소비자 테스트, 생산 이관 지원.",
        "skills": "식품개발 관능평가 레시피최적화 GC-MS HPLC 식품규격",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=R%26D%20%EC%8B%9D%ED%92%88%20%EC%97%B0%EA%B5%AC%EC%9B%90",
        "ncs_code": "21", "ncs_name": "식품가공",
        "tags": ["식품연구", "R&D", "신제품개발", "정규직"],
    },
    {
        "external_id": "w24-2026-FOOD-0003",
        "title": "바리스타 & 카페 매니저",
        "company": "스타벅스코리아",
        "location": "서울 (전 지점)",
        "salary": "2,800 ~ 3,500만원",
        "employment_type": "정규직",
        "deadline": "2026-05-31",
        "summary": "스타벅스 파트너(바리스타) 정규직 채용. 음료 제조, 고객 서비스, 재고 관리, 신입 교육. 바리스타 자격증 우대.",
        "skills": "에스프레소 라떼아트 고객서비스 재고관리 팀워크",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EB%B0%94%EB%A6%AC%EC%8A%A4%ED%83%80%20%26%20%EC%B9%B4%ED%8E%98%20%EB%A7%A4%EB%8B%88%EC%A0%80",
        "ncs_code": "13", "ncs_name": "음식서비스",
        "tags": ["바리스타", "카페", "스타벅스", "정규직"],
    },
    {
        "external_id": "w24-2026-FOOD-0004",
        "title": "호텔 조리사 (한식·양식)",
        "company": "롯데호텔앤리조트",
        "location": "서울 중구",
        "salary": "3,000 ~ 4,500만원",
        "employment_type": "정규직",
        "deadline": "2026-05-22",
        "summary": "5성급 호텔 레스토랑 한식·양식 조리. 메뉴 개발 참여, 위생 관리, 식재료 원가 절감, 연회 조리 지원.",
        "skills": "한식조리 양식조리 위생관리 메뉴개발 식재료관리 연회",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%ED%98%B8%ED%85%94%20%EC%A1%B0%EB%A6%AC%EC%82%AC%20%28%ED%95%9C%EC%8B%9D%C2%B7%EC%96%91%EC%8B%9D%29",
        "ncs_code": "13", "ncs_name": "음식서비스",
        "tags": ["호텔조리사", "한식", "양식", "정규직"],
    },
    {
        "external_id": "w24-2026-HEALTH-0003",
        "title": "임상 연구원 (CRA)",
        "company": "한국노바티스",
        "location": "서울 강남구",
        "salary": "4,500 ~ 7,000만원",
        "employment_type": "정규직",
        "deadline": "2026-05-28",
        "summary": "다국가 임상시험 모니터링 및 관리. IRB 대응, 프로토콜 준수 확인, 데이터 품질 관리, 규제 문서 작성.",
        "skills": "임상시험 GCP ICH 임상모니터링 의학지식 규제문서",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EC%9E%84%EC%83%81%20%EC%97%B0%EA%B5%AC%EC%9B%90%20%28CRA%29",
        "ncs_code": "06", "ncs_name": "보건의료",
        "tags": ["CRA", "임상시험", "제약", "정규직"],
    },
    {
        "external_id": "w24-2026-HEALTH-0004",
        "title": "정신건강 사회복지사",
        "company": "국립정신건강센터",
        "location": "서울 광진구",
        "salary": "3,000 ~ 3,800만원",
        "employment_type": "정규직",
        "deadline": "2026-05-11",
        "summary": "정신질환자 지역사회 복귀 지원 및 사례관리. 정신건강 상담, 재활 프로그램 운영, 가족 교육, 위기 개입.",
        "skills": "정신건강 사례관리 상담 위기개입 재활프로그램 사회복지사",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EC%A0%95%EC%8B%A0%EA%B1%B4%EA%B0%95%20%EC%82%AC%ED%9A%8C%EB%B3%B5%EC%A7%80%EC%82%AC",
        "ncs_code": "07", "ncs_name": "사회복지종교",
        "tags": ["정신건강사회복지사", "상담", "재활", "정규직"],
    },
    {
        "external_id": "w24-2026-ENV-0003",
        "title": "온실가스 검증 전문가",
        "company": "한국품질재단",
        "location": "서울 강남구",
        "salary": "4,000 ~ 5,500만원",
        "employment_type": "정규직",
        "deadline": "2026-05-25",
        "summary": "기업 온실가스 배출량 검증 및 탄소중립 컨설팅. ISO 14064 기준 검증, 탄소배출권 거래제 지원, ESG 보고서 검토.",
        "skills": "온실가스검증 ISO14064 탄소배출권 ESG 환경감사 LCA",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EC%98%A8%EC%8B%A4%EA%B0%80%EC%8A%A4%20%EA%B2%80%EC%A6%9D%20%EC%A0%84%EB%AC%B8%EA%B0%80",
        "ncs_code": "23", "ncs_name": "환경에너지안전",
        "tags": ["온실가스", "ESG", "탄소중립", "정규직"],
    },
    {
        "external_id": "w24-2026-ENV-0004",
        "title": "소방 설비 시공 감리원",
        "company": "한국소방시설관리협회 소속",
        "location": "경기 수원시",
        "salary": "3,800 ~ 5,200만원",
        "employment_type": "정규직",
        "deadline": "2026-05-13",
        "summary": "신축 건물 소방 설비 시공 감리 및 완공 검사. 소화·경보·피난 설비 시공 적합성 확인, 소방법령 검토.",
        "skills": "소방설비감리 소화설비 경보설비 소방법규 도면검토",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EC%86%8C%EB%B0%A9%20%EC%84%A4%EB%B9%84%20%EC%8B%9C%EA%B3%B5%20%EA%B0%90%EB%A6%AC%EC%9B%90",
        "ncs_code": "23", "ncs_name": "환경에너지안전",
        "tags": ["소방설비기사", "감리", "시공", "정규직"],
    },
    {
        "external_id": "w24-2026-DESIGN-0001",
        "title": "브랜드 디자이너",
        "company": "토스",
        "location": "서울 강남구",
        "salary": "4,500 ~ 7,500만원",
        "employment_type": "정규직",
        "deadline": "2026-06-08",
        "summary": "금융 브랜드 아이덴티티 설계 및 마케팅 디자인. 캠페인 비주얼 디렉션, 모션 그래픽, 브랜드 가이드라인 관리.",
        "skills": "Figma Illustrator After Effects 브랜딩 타이포그래피 모션그래픽",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EB%B8%8C%EB%9E%9C%EB%93%9C%20%EB%94%94%EC%9E%90%EC%9D%B4%EB%84%88",
        "ncs_code": "08", "ncs_name": "문화예술디자인방송",
        "tags": ["브랜드디자인", "모션그래픽", "핀테크", "정규직"],
    },
    {
        "external_id": "w24-2026-DESIGN-0002",
        "title": "영상 PD (유튜브·숏폼)",
        "company": "CJ ENM",
        "location": "서울 마포구",
        "salary": "3,500 ~ 5,500만원",
        "employment_type": "정규직",
        "deadline": "2026-05-29",
        "summary": "디지털 미디어 채널 영상 기획·제작·편집. 유튜브·틱톡·릴스 숏폼 콘텐츠 제작, 출연자 섭외, 후반 작업 지휘.",
        "skills": "영상기획 Premiere Pro After Effects 콘텐츠전략 유튜브 숏폼",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EC%98%81%EC%83%81%20PD%20%28%EC%9C%A0%ED%8A%9C%EB%B8%8C%C2%B7%EC%88%8F%ED%8F%BC%29",
        "ncs_code": "08", "ncs_name": "문화예술디자인방송",
        "tags": ["영상PD", "유튜브", "숏폼", "정규직"],
    },
    {
        "external_id": "w24-2026-TRANS-0001",
        "title": "물류 센터 운영 매니저",
        "company": "CJ대한통운",
        "location": "경기 이천시",
        "salary": "3,800 ~ 5,500만원",
        "employment_type": "정규직",
        "deadline": "2026-05-16",
        "summary": "풀필먼트 센터 입출고·재고·배송 운영 관리. KPI 모니터링, 인력 배치 최적화, 고객사 SLA 관리.",
        "skills": "WMS 물류운영 재고관리 KPI SCM 팀리더십",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EB%AC%BC%EB%A5%98%20%EC%84%BC%ED%84%B0%20%EC%9A%B4%EC%98%81%20%EB%A7%A4%EB%8B%88%EC%A0%80",
        "ncs_code": "09", "ncs_name": "운전운송",
        "tags": ["물류관리", "풀필먼트", "CJ대한통운", "정규직"],
    },
    {
        "external_id": "w24-2026-AGRI-0001",
        "title": "스마트팜 운영 기사",
        "company": "GS그룹 스마트팜",
        "location": "경북 상주시",
        "salary": "3,200 ~ 4,500만원",
        "employment_type": "정규직",
        "deadline": "2026-05-20",
        "summary": "ICT 기반 스마트 온실 환경 제어·데이터 분석·작물 생산 관리. 자동화 시스템 모니터링, 생산성 향상 제안.",
        "skills": "스마트팜 온실제어 IoT 데이터분석 작물재배 환경제어",
        "url": "https://www.work24.go.kr/wk/a/b/1200/retriveSrchEmpInfoList.do?schTxt=%EC%8A%A4%EB%A7%88%ED%8A%B8%ED%8C%9C%20%EC%9A%B4%EC%98%81%20%EA%B8%B0%EC%82%AC",
        "ncs_code": "24", "ncs_name": "농림어업",
        "tags": ["스마트팜", "IoT", "농업", "정규직"],
    },
]
